alter session set container=DBDOCK_01;

GRANT CREATE USER TO THE;

GRANT CONNECT TO THE;
GRANT RESOURCE TO THE;
GRANT CREATE SESSION TO THE;
GRANT CREATE ANY TABLE TO THE;
GRANT CREATE ANY INDEX TO THE;
GRANT ALTER ANY TABLE TO THE;
GRANT CREATE ANY VIEW TO THE;

-- -- going nuclear!
GRANT ALL privileges to THE;
