
  CREATE TABLE "THE"."TREE_SPECIES_CODE" 
   (	"TREE_SPECIES_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."TSC_PK" ON "THE"."TREE_SPECIES_CODE" ("TREE_SPECIES_CODE") 
  ;
ALTER TABLE "THE"."TREE_SPECIES_CODE" ADD CONSTRAINT "TSC_PK" PRIMARY KEY ("TREE_SPECIES_CODE")
  USING INDEX "THE"."TSC_PK"  ENABLE;
