
  CREATE TABLE "THE"."STOCKING_STATUS_CODE" 
   (	"STOCKING_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SSC6_PK" ON "THE"."STOCKING_STATUS_CODE" ("STOCKING_STATUS_CODE") 
  ;
ALTER TABLE "THE"."STOCKING_STATUS_CODE" ADD CONSTRAINT "SSC6_PK" PRIMARY KEY ("STOCKING_STATUS_CODE")
  USING INDEX "THE"."SSC6_PK"  ENABLE;
