
  CREATE TABLE "THE"."AGE_CLASS_CODE" 
   (	"AGE_CLASS_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."ACC_PK" ON "THE"."AGE_CLASS_CODE" ("AGE_CLASS_CODE") 
  ;
ALTER TABLE "THE"."AGE_CLASS_CODE" ADD CONSTRAINT "ACC_PK" PRIMARY KEY ("AGE_CLASS_CODE")
  USING INDEX "THE"."ACC_PK"  ENABLE;
