
  CREATE TABLE "THE"."TSB_NUMBER_CODE" 
   (	"TSB_NUMBER_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."TSBNC_PK" ON "THE"."TSB_NUMBER_CODE" ("TSB_NUMBER_CODE") 
  ;
ALTER TABLE "THE"."TSB_NUMBER_CODE" ADD CONSTRAINT "TSBNC_PK" PRIMARY KEY ("TSB_NUMBER_CODE")
  USING INDEX "THE"."TSBNC_PK"  ENABLE;
