
  CREATE TABLE "THE"."HEIGHT_CLASS_CODE" 
   (	"HEIGHT_CLASS_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."HCC_PK" ON "THE"."HEIGHT_CLASS_CODE" ("HEIGHT_CLASS_CODE") 
  ;
ALTER TABLE "THE"."HEIGHT_CLASS_CODE" ADD CONSTRAINT "HCC_PK" PRIMARY KEY ("HEIGHT_CLASS_CODE")
  USING INDEX "THE"."HCC_PK"  ENABLE;
