
  CREATE TABLE "THE"."STOCKING_CLASS_CODE" 
   (	"STOCKING_CLASS_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SCC1_PK" ON "THE"."STOCKING_CLASS_CODE" ("STOCKING_CLASS_CODE") 
  ;
ALTER TABLE "THE"."STOCKING_CLASS_CODE" ADD CONSTRAINT "SCC1_PK" PRIMARY KEY ("STOCKING_CLASS_CODE")
  USING INDEX "THE"."SCC1_PK"  ENABLE;
