
  CREATE TABLE "THE"."SITE_INDEX_SOURCE_CODE" 
   (	"SITE_INDEX_SOURCE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SISC_PK" ON "THE"."SITE_INDEX_SOURCE_CODE" ("SITE_INDEX_SOURCE_CODE") 
  ;
ALTER TABLE "THE"."SITE_INDEX_SOURCE_CODE" ADD CONSTRAINT "SISC_PK" PRIMARY KEY ("SITE_INDEX_SOURCE_CODE")
  USING INDEX "THE"."SISC_PK"  ENABLE;
