
  CREATE TABLE "THE"."OPEN_CATEGORY_CODE" 
   (	"OPEN_CATEGORY_CODE" VARCHAR2(7) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."OCC_PK" ON "THE"."OPEN_CATEGORY_CODE" ("OPEN_CATEGORY_CODE") 
  ;
ALTER TABLE "THE"."OPEN_CATEGORY_CODE" ADD CONSTRAINT "OCC_PK" PRIMARY KEY ("OPEN_CATEGORY_CODE")
  USING INDEX "THE"."OCC_PK"  ENABLE;
