
  CREATE TABLE "THE"."OPENING_STATUS_CODE" 
   (	"OPENING_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."OSC_PK" ON "THE"."OPENING_STATUS_CODE" ("OPENING_STATUS_CODE") 
  ;
ALTER TABLE "THE"."OPENING_STATUS_CODE" ADD CONSTRAINT "OSC_PK" PRIMARY KEY ("OPENING_STATUS_CODE")
  USING INDEX "THE"."OSC_PK"  ENABLE;
