
   CREATE SEQUENCE  "THE"."FOREST_CLIENT_AUDIT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 515452 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE TABLE "THE"."CLIENT_UPDATE_ACTION_CODE" 
   (	"CLIENT_UPDATE_ACTION_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CUAC_PK" PRIMARY KEY ("CLIENT_UPDATE_ACTION_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_AUDIT_CODE" 
   (	"CLIENT_AUDIT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CAUDC_PK" PRIMARY KEY ("CLIENT_AUDIT_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."FOR_CLI_AUDIT" 
   (	"FOREST_CLIENT_AUDIT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"CLIENT_AUDIT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"LEGAL_FIRST_NAME" VARCHAR2(30), 
	"LEGAL_MIDDLE_NAME" VARCHAR2(30), 
	"CLIENT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"BIRTHDATE" DATE, 
	"CLIENT_ID_TYPE_CODE" VARCHAR2(4), 
	"CLIENT_IDENTIFICATION" VARCHAR2(40), 
	"REGISTRY_COMPANY_TYPE_CODE" VARCHAR2(4), 
	"CORP_REGN_NMBR" VARCHAR2(9), 
	"CLIENT_ACRONYM" VARCHAR2(8), 
	"WCB_FIRM_NUMBER" VARCHAR2(6), 
	"OCG_SUPPLIER_NMBR" VARCHAR2(10), 
	"CLIENT_COMMENT" VARCHAR2(4000), 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "FCAUD_PK" PRIMARY KEY ("FOREST_CLIENT_AUDIT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FCA_OU_FK" FOREIGN KEY ("ADD_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "FCA_FC_FK" FOREIGN KEY ("CLIENT_NUMBER")
	  REFERENCES "THE"."FOREST_CLIENT" ("CLIENT_NUMBER") ENABLE, 
	 CONSTRAINT "FCA_CAUDC_FK" FOREIGN KEY ("CLIENT_AUDIT_CODE")
	  REFERENCES "THE"."CLIENT_AUDIT_CODE" ("CLIENT_AUDIT_CODE") ENABLE, 
	 CONSTRAINT "FCA_OU_IS_UPDATED_BY_FK" FOREIGN KEY ("UPDATE_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE
   ) ;
