
  CREATE TABLE "THE"."SILV_MILESTONE_TYPE_CODE" 
   (	"SILV_MILESTONE_TYPE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SMTC2_PK" ON "THE"."SILV_MILESTONE_TYPE_CODE" ("SILV_MILESTONE_TYPE_CODE") 
  ;
ALTER TABLE "THE"."SILV_MILESTONE_TYPE_CODE" ADD CONSTRAINT "SMTC2_PK" PRIMARY KEY ("SILV_MILESTONE_TYPE_CODE")
  USING INDEX "THE"."SMTC2_PK"  ENABLE;

  CREATE TABLE "THE"."STOCKING_STANDARD_UNIT_AMD" 
   (	"STOCKING_STANDARD_UNIT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OPENING_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"STANDARDS_UNIT_ID" VARCHAR2(4) NOT NULL ENABLE, 
	"STANDARDS_REGIME_ID" NUMBER(10,0), 
	"NET_AREA" NUMBER(7,1) NOT NULL ENABLE, 
	"MAX_ALLOW_SOIL_DISTURBANCE_PCT" NUMBER(3,1), 
	"VARIANCE_IND" VARCHAR2(1), 
	"REGEN_DELAY_OFFSET_YRS" NUMBER(2,0), 
	"REGEN_OBLIGATION_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"NO_REGEN_EARLY_OFFSET_YRS" NUMBER(2,0), 
	"NO_REGEN_LATE_OFFSET_YRS" NUMBER(2,0), 
	"FREE_GROWING_EARLY_OFFSET_YRS" NUMBER(2,0), 
	"FREE_GROWING_LATE_OFFSET_YRS" NUMBER(2,0), 
	"AMENDMENT_RATIONALE_COMMENT" VARCHAR2(2000), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SSUAMD_PK" PRIMARY KEY ("STOCKING_STANDARD_UNIT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AVCON_1080773726_REGEN_000" CHECK (REGEN_OBLIGATION_IND IN ('N', 'Y')) ENABLE
   ) ;

  CREATE TABLE "THE"."STOCKING_MILESTONE" 
   (	"STOCKING_STANDARD_UNIT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SILV_MILESTONE_TYPE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"RESULTS_SUBMISSION_ID" NUMBER(10,0), 
	"DECLARED_DATE" DATE, 
	"DECLARED_USERID" VARCHAR2(30), 
	"DECLARE_IND" VARCHAR2(1), 
	"DECLARATION_SUBMITTED_DATE" DATE, 
	"EARLY_OFFSET_YEARS" NUMBER(2,0), 
	"LATE_OFFSET_YEARS" NUMBER(2,0), 
	"DUE_EARLY_DATE" DATE, 
	"DUE_LATE_DATE" DATE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"EXTENT_FEASIBLE_DECLARED_IND" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "SM_SMTC_FK" FOREIGN KEY ("SILV_MILESTONE_TYPE_CODE")
	  REFERENCES "THE"."SILV_MILESTONE_TYPE_CODE" ("SILV_MILESTONE_TYPE_CODE") ENABLE, 
	 CONSTRAINT "SM_SSU_FK" FOREIGN KEY ("STOCKING_STANDARD_UNIT_ID")
	  REFERENCES "THE"."STOCKING_STANDARD_UNIT" ("STOCKING_STANDARD_UNIT_ID") ENABLE, 
	 CONSTRAINT "SM_RES_FK" FOREIGN KEY ("RESULTS_SUBMISSION_ID")
	  REFERENCES "THE"."RESULTS_ELECTRONIC_SUBMISSION" ("RESULTS_SUBMISSION_ID") ENABLE
   )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "THE"."SM_PK" ON "THE"."STOCKING_MILESTONE" ("STOCKING_STANDARD_UNIT_ID", "SILV_MILESTONE_TYPE_CODE") 
  ;
ALTER TABLE "THE"."STOCKING_MILESTONE" ADD CONSTRAINT "SM_PK" PRIMARY KEY ("STOCKING_STANDARD_UNIT_ID", "SILV_MILESTONE_TYPE_CODE")
  USING INDEX "THE"."SM_PK"  ENABLE;
