
  CREATE TABLE "THE"."RESULTS_AUDIT_ACTION_CODE" 
   (	"RESULTS_AUDIT_ACTION_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."RAAC_PK" ON "THE"."RESULTS_AUDIT_ACTION_CODE" ("RESULTS_AUDIT_ACTION_CODE") 
  ;
ALTER TABLE "THE"."RESULTS_AUDIT_ACTION_CODE" ADD CONSTRAINT "RAAC_PK" PRIMARY KEY ("RESULTS_AUDIT_ACTION_CODE")
  USING INDEX "THE"."RAAC_PK"  ENABLE;
