
  CREATE TABLE "THE"."ORG_UNIT" 
   (	"ORG_UNIT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ORG_UNIT_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"ORG_UNIT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"LOCATION_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"AREA_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"TELEPHONE_NO" VARCHAR2(7) NOT NULL ENABLE, 
	"ORG_LEVEL_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"OFFICE_NAME_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"ROLLUP_REGION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLLUP_REGION_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"ROLLUP_DIST_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLLUP_DIST_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE
   ) ;
  CREATE UNIQUE INDEX "THE"."I1$_ORG_UNIT" ON "THE"."ORG_UNIT" ("ORG_UNIT_NO") 
  ;
ALTER TABLE "THE"."ORG_UNIT" ADD CONSTRAINT "ORG_UNIT_PK" PRIMARY KEY ("ORG_UNIT_NO")
  USING INDEX "THE"."I1$_ORG_UNIT"  ENABLE;

  CREATE TABLE "THE"."SILV_ADMIN_ZONE" 
   (	"DIST_ADMIN_ZONE" VARCHAR2(2) NOT NULL ENABLE, 
	"ORG_UNIT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ADMIN_ZONE_DESC" VARCHAR2(50) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SAZ_OU_FK" FOREIGN KEY ("ORG_UNIT_NO")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SILV_ADMIN_ZONE_PK" ON "THE"."SILV_ADMIN_ZONE" ("ORG_UNIT_NO", "DIST_ADMIN_ZONE") 
  ;
ALTER TABLE "THE"."SILV_ADMIN_ZONE" ADD CONSTRAINT "SILV_ADMIN_ZONE_PK" PRIMARY KEY ("ORG_UNIT_NO", "DIST_ADMIN_ZONE")
  USING INDEX "THE"."SILV_ADMIN_ZONE_PK"  ENABLE;

  CREATE TABLE "THE"."CLIENT_ID_TYPE_CODE" 
   (	"CLIENT_ID_TYPE_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CITC_PK" PRIMARY KEY ("CLIENT_ID_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_TYPE_CODE" 
   (	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CTCD_PK" PRIMARY KEY ("CLIENT_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."REGISTRY_COMPANY_TYPE_CODE" 
   (	"REGISTRY_COMPANY_TYPE_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CRCTC_PK" PRIMARY KEY ("REGISTRY_COMPANY_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_TYPE_COMPANY_XREF" 
   (	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"REGISTRY_COMPANY_TYPE_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CTCX_PK" PRIMARY KEY ("CLIENT_TYPE_CODE", "REGISTRY_COMPANY_TYPE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CTCX_CTC_FK" FOREIGN KEY ("CLIENT_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_TYPE_CODE" ("CLIENT_TYPE_CODE") ENABLE, 
	 CONSTRAINT "CTCX_CRCTC_FK" FOREIGN KEY ("REGISTRY_COMPANY_TYPE_CODE")
	  REFERENCES "THE"."REGISTRY_COMPANY_TYPE_CODE" ("REGISTRY_COMPANY_TYPE_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_STATUS_CODE" 
   (	"CLIENT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."CSTC_PK" ON "THE"."CLIENT_STATUS_CODE" ("CLIENT_STATUS_CODE") 
  ;
ALTER TABLE "THE"."CLIENT_STATUS_CODE" ADD CONSTRAINT "CSTC_PK" PRIMARY KEY ("CLIENT_STATUS_CODE")
  USING INDEX "THE"."CSTC_PK"  ENABLE;

  CREATE TABLE "THE"."FOREST_CLIENT" 
   (	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"LEGAL_FIRST_NAME" VARCHAR2(30), 
	"LEGAL_MIDDLE_NAME" VARCHAR2(30), 
	"CLIENT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"BIRTHDATE" DATE, 
	"CLIENT_ID_TYPE_CODE" VARCHAR2(4), 
	"CLIENT_IDENTIFICATION" VARCHAR2(40), 
	"REGISTRY_COMPANY_TYPE_CODE" VARCHAR2(4), 
	"CORP_REGN_NMBR" VARCHAR2(9), 
	"CLIENT_ACRONYM" VARCHAR2(8), 
	"WCB_FIRM_NUMBER" VARCHAR2(6), 
	"OCG_SUPPLIER_NMBR" VARCHAR2(10), 
	"CLIENT_COMMENT" VARCHAR2(4000), 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "FOREST_CLIENT_PK" PRIMARY KEY ("CLIENT_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FC_OU_FK" FOREIGN KEY ("ADD_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "FC_CITC_FK" FOREIGN KEY ("CLIENT_ID_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_ID_TYPE_CODE" ("CLIENT_ID_TYPE_CODE") ENABLE, 
	 CONSTRAINT "FC_CSC_FK" FOREIGN KEY ("CLIENT_STATUS_CODE")
	  REFERENCES "THE"."CLIENT_STATUS_CODE" ("CLIENT_STATUS_CODE") ENABLE, 
	 CONSTRAINT "FC_CTCX_FK" FOREIGN KEY ("CLIENT_TYPE_CODE", "REGISTRY_COMPANY_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_TYPE_COMPANY_XREF" ("CLIENT_TYPE_CODE", "REGISTRY_COMPANY_TYPE_CODE") ENABLE, 
	 CONSTRAINT "FC_OU_IS_UPDATED_BY_FK" FOREIGN KEY ("UPDATE_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_LOCATION" 
   (	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"CLIENT_LOCN_NAME" VARCHAR2(40), 
	"HDBS_COMPANY_CODE" VARCHAR2(5), 
	"ADDRESS_1" VARCHAR2(40) NOT NULL ENABLE, 
	"ADDRESS_2" VARCHAR2(40), 
	"ADDRESS_3" VARCHAR2(40), 
	"CITY" VARCHAR2(30) NOT NULL ENABLE, 
	"PROVINCE" VARCHAR2(50), 
	"POSTAL_CODE" VARCHAR2(10), 
	"COUNTRY" VARCHAR2(50) NOT NULL ENABLE, 
	"BUSINESS_PHONE" VARCHAR2(10), 
	"HOME_PHONE" VARCHAR2(10), 
	"CELL_PHONE" VARCHAR2(10), 
	"FAX_NUMBER" VARCHAR2(10), 
	"EMAIL_ADDRESS" VARCHAR2(128), 
	"LOCN_EXPIRED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"RETURNED_MAIL_DATE" DATE, 
	"TRUST_LOCATION_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"CLI_LOCN_COMMENT" VARCHAR2(4000), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "CLIENT_LOCATION_PK" PRIMARY KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CL_FC_FK" FOREIGN KEY ("CLIENT_NUMBER")
	  REFERENCES "THE"."FOREST_CLIENT" ("CLIENT_NUMBER") ENABLE, 
	 CONSTRAINT "CL_OU_FK" FOREIGN KEY ("UPDATE_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "CL_OU_IS_CREATED_BY_FK" FOREIGN KEY ("ADD_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE
   ) ;

  CREATE TABLE "THE"."RESULTS_ELECTRONIC_SUBMISSION" 
   (	"RESULTS_SUBMISSION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SUBMISSION_TIMESTAMP" DATE NOT NULL ENABLE, 
	"SUBMITTED_BY" VARCHAR2(30) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8), 
	"CLIENT_LOCN_CODE" VARCHAR2(2), 
	"ORG_UNIT_NO" NUMBER(10,0), 
	"USER_FILENAME" VARCHAR2(50), 
	"USER_REFERENCE" VARCHAR2(240), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "RES_CN_FK" FOREIGN KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "RES_OU_FK" FOREIGN KEY ("ORG_UNIT_NO")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE
   )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "THE"."RES_PK" ON "THE"."RESULTS_ELECTRONIC_SUBMISSION" ("RESULTS_SUBMISSION_ID") 
  ;
ALTER TABLE "THE"."RESULTS_ELECTRONIC_SUBMISSION" ADD CONSTRAINT "RES_PK" PRIMARY KEY ("RESULTS_SUBMISSION_ID")
  USING INDEX "THE"."RES_PK"  ENABLE;

  CREATE TABLE "THE"."OPENING" 
   (	"OPENING_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"GEO_DISTRICT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ADMIN_DISTRICT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"MAPSHEET_GRID" VARCHAR2(3), 
	"MAPSHEET_LETTER" VARCHAR2(1), 
	"MAPSHEET_SQUARE" VARCHAR2(3), 
	"MAPSHEET_QUAD" VARCHAR2(1), 
	"MAPSHEET_SUB_QUAD" VARCHAR2(1), 
	"OPENING_NUMBER" VARCHAR2(4), 
	"OPENING_LOCN_NAME" VARCHAR2(30), 
	"OPEN_CATEGORY_CODE" VARCHAR2(7) NOT NULL ENABLE, 
	"LICENSEE_OPENING_ID" VARCHAR2(30), 
	"TSB_NUMBER_CODE" VARCHAR2(3), 
	"OPENING_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"ORG_UNIT_NO" NUMBER(10,0), 
	"DIST_ADMIN_ZONE" VARCHAR2(2), 
	"MAX_ALLOW_PERMNT_ACCESS_PCT" NUMBER(3,1), 
	"PREV_AGE_CLASS_CODE" VARCHAR2(1), 
	"PREV_SITE_INDEX" NUMBER(5,0), 
	"PREV_SITE_INDEX_SOURCE_CODE" VARCHAR2(1), 
	"PREV_HEIGHT_CLASS_CODE" VARCHAR2(1), 
	"PREV_SITE_CLASS_CODE" VARCHAR2(1), 
	"PREV_STOCKING_CLASS_CODE" VARCHAR2(1), 
	"PREV_STOCKING_STATUS_CODE" VARCHAR2(3), 
	"PREV_TREE_SPP1_CODE" VARCHAR2(8), 
	"PREV_TREE_SPP2_CODE" VARCHAR2(8), 
	"APP_ENT_BY_USERID" VARCHAR2(30), 
	"APPROVE_DATE" DATE, 
	"AMENDMENT_IND" VARCHAR2(1), 
	"RESULTS_SUBMISSION_ID" NUMBER(10,0), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "O_ACC_FK" FOREIGN KEY ("PREV_AGE_CLASS_CODE")
	  REFERENCES "THE"."AGE_CLASS_CODE" ("AGE_CLASS_CODE") ENABLE, 
	 CONSTRAINT "O_SCC2_FK" FOREIGN KEY ("PREV_SITE_CLASS_CODE")
	  REFERENCES "THE"."SITE_CLASS_CODE" ("SITE_CLASS_CODE") ENABLE, 
	 CONSTRAINT "O_TSC2_FK" FOREIGN KEY ("PREV_TREE_SPP2_CODE")
	  REFERENCES "THE"."TREE_SPECIES_CODE" ("TREE_SPECIES_CODE") ENABLE, 
	 CONSTRAINT "O_OSC_FK" FOREIGN KEY ("OPENING_STATUS_CODE")
	  REFERENCES "THE"."OPENING_STATUS_CODE" ("OPENING_STATUS_CODE") ENABLE, 
	 CONSTRAINT "O_OU_FK" FOREIGN KEY ("ADMIN_DISTRICT_NO")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "O_TNC1_FK" FOREIGN KEY ("TSB_NUMBER_CODE")
	  REFERENCES "THE"."TSB_NUMBER_CODE" ("TSB_NUMBER_CODE") ENABLE, 
	 CONSTRAINT "O_OCC_FK" FOREIGN KEY ("OPEN_CATEGORY_CODE")
	  REFERENCES "THE"."OPEN_CATEGORY_CODE" ("OPEN_CATEGORY_CODE") ENABLE, 
	 CONSTRAINT "O_HCC_FK" FOREIGN KEY ("PREV_HEIGHT_CLASS_CODE")
	  REFERENCES "THE"."HEIGHT_CLASS_CODE" ("HEIGHT_CLASS_CODE") ENABLE, 
	 CONSTRAINT "O_RES_FK" FOREIGN KEY ("RESULTS_SUBMISSION_ID")
	  REFERENCES "THE"."RESULTS_ELECTRONIC_SUBMISSION" ("RESULTS_SUBMISSION_ID") ENABLE, 
	 CONSTRAINT "O_SISC_FK" FOREIGN KEY ("PREV_SITE_INDEX_SOURCE_CODE")
	  REFERENCES "THE"."SITE_INDEX_SOURCE_CODE" ("SITE_INDEX_SOURCE_CODE") ENABLE, 
	 CONSTRAINT "O_SSC6_FK" FOREIGN KEY ("PREV_STOCKING_STATUS_CODE")
	  REFERENCES "THE"."STOCKING_STATUS_CODE" ("STOCKING_STATUS_CODE") ENABLE, 
	 CONSTRAINT "O_SAZ_FK" FOREIGN KEY ("ORG_UNIT_NO", "DIST_ADMIN_ZONE")
	  REFERENCES "THE"."SILV_ADMIN_ZONE" ("ORG_UNIT_NO", "DIST_ADMIN_ZONE") ENABLE, 
	 CONSTRAINT "O_OU_RESIDES_WITHIN_FK" FOREIGN KEY ("GEO_DISTRICT_NO")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "O_TSC1_FK" FOREIGN KEY ("PREV_TREE_SPP1_CODE")
	  REFERENCES "THE"."TREE_SPECIES_CODE" ("TREE_SPECIES_CODE") ENABLE, 
	 CONSTRAINT "O_SCC1_FK" FOREIGN KEY ("PREV_STOCKING_CLASS_CODE")
	  REFERENCES "THE"."STOCKING_CLASS_CODE" ("STOCKING_CLASS_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."O_PK" ON "THE"."OPENING" ("OPENING_ID") 
  ;
ALTER TABLE "THE"."OPENING" ADD CONSTRAINT "O_PK" PRIMARY KEY ("OPENING_ID")
  USING INDEX "THE"."O_PK"  ENABLE;

  CREATE TABLE "THE"."REFOREST_DECLARE_TYPE_CODE" 
   (	"REFOREST_DECLARE_TYPE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "REDTC_PK" PRIMARY KEY ("REFOREST_DECLARE_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CUT_REGULATION_CODE" 
   (	"CUT_REGULATION_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CURC_PK" PRIMARY KEY ("CUT_REGULATION_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."BLOCK_STATUS_CODE" 
   (	"BLOCK_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."BSCD_PK" ON "THE"."BLOCK_STATUS_CODE" ("BLOCK_STATUS_CODE") 
  ;
ALTER TABLE "THE"."BLOCK_STATUS_CODE" ADD CONSTRAINT "BSCD_PK" PRIMARY KEY ("BLOCK_STATUS_CODE")
  USING INDEX "THE"."BSCD_PK"  ENABLE;

  CREATE TABLE "THE"."MGMT_UNIT_TYPE_CODE" 
   (	"MGMT_UNIT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."MUTC_PK" ON "THE"."MGMT_UNIT_TYPE_CODE" ("MGMT_UNIT_TYPE_CODE") 
  ;
ALTER TABLE "THE"."MGMT_UNIT_TYPE_CODE" ADD CONSTRAINT "MUTC_PK" PRIMARY KEY ("MGMT_UNIT_TYPE_CODE")
  USING INDEX "THE"."MUTC_PK"  ENABLE;

  CREATE TABLE "THE"."FOREST_MGMT_UNIT" 
   (	"MGMT_SKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"MGMT_UNIT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"MGMT_UNIT_ID" VARCHAR2(4), 
	"DESCRIPTION" VARCHAR2(100), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "FMU_MUTC_FK" FOREIGN KEY ("MGMT_UNIT_TYPE_CODE")
	  REFERENCES "THE"."MGMT_UNIT_TYPE_CODE" ("MGMT_UNIT_TYPE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."FMU_UK1" ON "THE"."FOREST_MGMT_UNIT" ("MGMT_UNIT_ID", "MGMT_UNIT_TYPE_CODE") 
  ;
  CREATE UNIQUE INDEX "THE"."FMU_PK" ON "THE"."FOREST_MGMT_UNIT" ("MGMT_SKEY") 
  ;
ALTER TABLE "THE"."FOREST_MGMT_UNIT" ADD CONSTRAINT "FMU_UK1" UNIQUE ("MGMT_UNIT_ID", "MGMT_UNIT_TYPE_CODE")
  USING INDEX "THE"."FMU_UK1"  ENABLE;
ALTER TABLE "THE"."FOREST_MGMT_UNIT" ADD CONSTRAINT "FMU_PK" PRIMARY KEY ("MGMT_SKEY")
  USING INDEX "THE"."FMU_PK"  ENABLE;

  CREATE TABLE "THE"."TENURE_FILE_STATUS_CODE" 
   (	"TENURE_FILE_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."TFSCD_PK" ON "THE"."TENURE_FILE_STATUS_CODE" ("TENURE_FILE_STATUS_CODE") 
  ;
ALTER TABLE "THE"."TENURE_FILE_STATUS_CODE" ADD CONSTRAINT "TFSCD_PK" PRIMARY KEY ("TENURE_FILE_STATUS_CODE")
  USING INDEX "THE"."TFSCD_PK"  ENABLE;

  CREATE TABLE "THE"."FILE_TYPE_CODE" 
   (	"FILE_TYPE_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."FT_CD_PK" ON "THE"."FILE_TYPE_CODE" ("FILE_TYPE_CODE") 
  ;
ALTER TABLE "THE"."FILE_TYPE_CODE" ADD CONSTRAINT "FT_CD_PK" PRIMARY KEY ("FILE_TYPE_CODE")
  USING INDEX "THE"."FT_CD_PK"  ENABLE;

  CREATE TABLE "THE"."PROV_FOREST_USE" 
   (	"FOREST_FILE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"FILE_STATUS_ST" VARCHAR2(3), 
	"FILE_STATUS_DATE" DATE, 
	"FILE_TYPE_CODE" VARCHAR2(3), 
	"FOREST_REGION" NUMBER(10,0) NOT NULL ENABLE, 
	"BCTS_ORG_UNIT" NUMBER(10,0), 
	"SB_FUNDED_IND" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"DISTRICT_ADMIN_ZONE" VARCHAR2(4), 
	"MGMT_UNIT_TYPE" VARCHAR2(1), 
	"MGMT_UNIT_ID" VARCHAR2(4), 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"FOREST_TENURE_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	 CONSTRAINT "AVCON_1148331360_SB_FU_001" CHECK (
SB_FUNDED_IND IN ('N', 'Y')
) ENABLE, 
	 CONSTRAINT "PFU_GUID_UK" UNIQUE ("FOREST_TENURE_GUID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PFU_OU_FK" FOREIGN KEY ("FOREST_REGION")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "PFU_TFSCD_FK" FOREIGN KEY ("FILE_STATUS_ST")
	  REFERENCES "THE"."TENURE_FILE_STATUS_CODE" ("TENURE_FILE_STATUS_CODE") ENABLE, 
	 CONSTRAINT "PFU_BCTS_OU_FK" FOREIGN KEY ("BCTS_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "PFU_FMU_FK" FOREIGN KEY ("MGMT_UNIT_ID", "MGMT_UNIT_TYPE")
	  REFERENCES "THE"."FOREST_MGMT_UNIT" ("MGMT_UNIT_ID", "MGMT_UNIT_TYPE_CODE") ENABLE, 
	 CONSTRAINT "PFU_FTCD_FK" FOREIGN KEY ("FILE_TYPE_CODE")
	  REFERENCES "THE"."FILE_TYPE_CODE" ("FILE_TYPE_CODE") ENABLE
   ) ;
  CREATE INDEX "THE"."PFU_I2" ON "THE"."PROV_FOREST_USE" ("FOREST_FILE_ID", "FILE_TYPE_CODE", "FILE_STATUS_ST") 
  ;
ALTER TABLE "THE"."PROV_FOREST_USE" ADD CONSTRAINT "PFU_PK" PRIMARY KEY ("FOREST_FILE_ID")
  USING INDEX "THE"."PFU_I2"  ENABLE;

  CREATE TABLE "THE"."CASCADE_SPLIT_CODE" 
   (	"CASCADE_SPLIT_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."CASCD_PK" ON "THE"."CASCADE_SPLIT_CODE" ("CASCADE_SPLIT_CODE") 
  ;
ALTER TABLE "THE"."CASCADE_SPLIT_CODE" ADD CONSTRAINT "CASCD_PK" PRIMARY KEY ("CASCADE_SPLIT_CODE")
  USING INDEX "THE"."CASCD_PK"  ENABLE;

  CREATE TABLE "THE"."QUOTA_TYPE_CODE" 
   (	"QUOTA_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."QTCD_PK" ON "THE"."QUOTA_TYPE_CODE" ("QUOTA_TYPE_CODE") 
  ;
ALTER TABLE "THE"."QUOTA_TYPE_CODE" ADD CONSTRAINT "QTCD_PK" PRIMARY KEY ("QUOTA_TYPE_CODE")
  USING INDEX "THE"."QTCD_PK"  ENABLE;

  CREATE TABLE "THE"."SALVAGE_TYPE_CODE" 
   (	"SALVAGE_TYPE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "SALVTCD_PK" PRIMARY KEY ("SALVAGE_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CROWN_LANDS_REGION_CODE" 
   (	"CROWN_LANDS_REGION_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."CLRC_PK" ON "THE"."CROWN_LANDS_REGION_CODE" ("CROWN_LANDS_REGION_CODE") 
  ;
ALTER TABLE "THE"."CROWN_LANDS_REGION_CODE" ADD CONSTRAINT "CLRC_PK" PRIMARY KEY ("CROWN_LANDS_REGION_CODE")
  USING INDEX "THE"."CLRC_PK"  ENABLE;

  CREATE TABLE "THE"."MARKING_METHOD_CODE" 
   (	"MARKING_METHOD_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."MMCD_PK" ON "THE"."MARKING_METHOD_CODE" ("MARKING_METHOD_CODE") 
  ;
ALTER TABLE "THE"."MARKING_METHOD_CODE" ADD CONSTRAINT "MMCD_PK" PRIMARY KEY ("MARKING_METHOD_CODE")
  USING INDEX "THE"."MMCD_PK"  ENABLE;

  CREATE TABLE "THE"."MARK_EXTENSION_REASON_CODE" 
   (	"MARK_EXTENSION_REASON_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."MERCD_PK" ON "THE"."MARK_EXTENSION_REASON_CODE" ("MARK_EXTENSION_REASON_CODE") 
  ;
ALTER TABLE "THE"."MARK_EXTENSION_REASON_CODE" ADD CONSTRAINT "MERCD_PK" PRIMARY KEY ("MARK_EXTENSION_REASON_CODE")
  USING INDEX "THE"."MERCD_PK"  ENABLE;

  CREATE TABLE "THE"."MARKING_INSTRUMENT_CODE" 
   (	"MARKING_INSTRUMENT_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."MICD_PK" ON "THE"."MARKING_INSTRUMENT_CODE" ("MARKING_INSTRUMENT_CODE") 
  ;
ALTER TABLE "THE"."MARKING_INSTRUMENT_CODE" ADD CONSTRAINT "MICD_PK" PRIMARY KEY ("MARKING_INSTRUMENT_CODE")
  USING INDEX "THE"."MICD_PK"  ENABLE;

  CREATE TABLE "THE"."TIMBER_MARK" 
   (	"TIMBER_MARK" VARCHAR2(6) NOT NULL ENABLE, 
	"FOREST_FILE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CUTTING_PERMIT_ID" VARCHAR2(3) NOT NULL ENABLE, 
	"FOREST_DISTRICT" NUMBER(10,0) NOT NULL ENABLE, 
	"GEOGRAPHIC_DISTRCT" NUMBER(10,0) NOT NULL ENABLE, 
	"CASCADE_SPLIT_CODE" VARCHAR2(1), 
	"QUOTA_TYPE_CODE" VARCHAR2(1), 
	"DECIDUOUS_IND" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CATASTROPHIC_IND" VARCHAR2(1) DEFAULT NULL, 
	"CROWN_GRANTED_IND" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRUISE_BASED_IND" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CERTIFICATE" VARCHAR2(6), 
	"HDBS_TIMBER_MARK" VARCHAR2(7), 
	"VM_TIMBER_MARK" VARCHAR2(6), 
	"TENURE_TERM" NUMBER(5,0), 
	"BCAA_FOLIO_NUMBER" VARCHAR2(23), 
	"ACTIVATED_USERID" VARCHAR2(30), 
	"AMENDED_USERID" VARCHAR2(30), 
	"DISTRICT_ADMN_ZONE" VARCHAR2(4), 
	"GRANTED_ACQRD_DATE" DATE, 
	"LANDS_REGION" VARCHAR2(1), 
	"CROWN_GRANTED_ACQ_DESC" VARCHAR2(240), 
	"MARK_STATUS_ST" VARCHAR2(3), 
	"MARK_STATUS_DATE" DATE, 
	"MARK_AMEND_DATE" DATE, 
	"MARK_APPL_DATE" DATE, 
	"MARK_CANCEL_DATE" DATE, 
	"MARK_EXTEND_DATE" DATE, 
	"MARK_EXTEND_RSN_CD" VARCHAR2(1), 
	"MARK_EXTEND_COUNT" NUMBER(10,0), 
	"MARK_ISSUE_DATE" DATE, 
	"MARK_EXPIRY_DATE" DATE, 
	"MARKNG_INSTRMNT_CD" VARCHAR2(1), 
	"MARKING_METHOD_CD" VARCHAR2(1), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"SMALL_PATCH_SALVAGE_IND" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"SALVAGE_TYPE_CODE" VARCHAR2(3), 
	 CONSTRAINT "AVCON_1054232647_CRUIS_000" CHECK (CRUISE_BASED_IND IN ('N', 'Y')) ENABLE, 
	 CONSTRAINT "AVCON_1054232647_CROWN_001" CHECK (CROWN_GRANTED_IND IN ('N', 'Y')) ENABLE, 
	 CONSTRAINT "AVCON_1054232647_CATAS_000" CHECK (CATASTROPHIC_IND IN ('N', 'Y')) ENABLE, 
	 CONSTRAINT "AVCON_1054232647_DECID_000" CHECK (DECIDUOUS_IND IN ('N', 'Y')) ENABLE, 
	 CONSTRAINT "TM_PFU_FK" FOREIGN KEY ("FOREST_FILE_ID")
	  REFERENCES "THE"."PROV_FOREST_USE" ("FOREST_FILE_ID") ENABLE, 
	 CONSTRAINT "TM_CASCD_FK" FOREIGN KEY ("CASCADE_SPLIT_CODE")
	  REFERENCES "THE"."CASCADE_SPLIT_CODE" ("CASCADE_SPLIT_CODE") ENABLE, 
	 CONSTRAINT "TM_MERCD_FK" FOREIGN KEY ("MARK_EXTEND_RSN_CD")
	  REFERENCES "THE"."MARK_EXTENSION_REASON_CODE" ("MARK_EXTENSION_REASON_CODE") ENABLE, 
	 CONSTRAINT "TM_MICD_FK" FOREIGN KEY ("MARKNG_INSTRMNT_CD")
	  REFERENCES "THE"."MARKING_INSTRUMENT_CODE" ("MARKING_INSTRUMENT_CODE") ENABLE, 
	 CONSTRAINT "TFALLING_GEOGRAPHICALLY_WIT_FK" FOREIGN KEY ("GEOGRAPHIC_DISTRCT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "TM_OU_FK" FOREIGN KEY ("FOREST_DISTRICT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "TM_QTCD_FK" FOREIGN KEY ("QUOTA_TYPE_CODE")
	  REFERENCES "THE"."QUOTA_TYPE_CODE" ("QUOTA_TYPE_CODE") ENABLE, 
	 CONSTRAINT "TM_MMCD_FK" FOREIGN KEY ("MARKING_METHOD_CD")
	  REFERENCES "THE"."MARKING_METHOD_CODE" ("MARKING_METHOD_CODE") ENABLE, 
	 CONSTRAINT "TM_TSCD_FK" FOREIGN KEY ("MARK_STATUS_ST")
	  REFERENCES "THE"."TENURE_FILE_STATUS_CODE" ("TENURE_FILE_STATUS_CODE") ENABLE, 
	 CONSTRAINT "TM_CLRC_FK" FOREIGN KEY ("LANDS_REGION")
	  REFERENCES "THE"."CROWN_LANDS_REGION_CODE" ("CROWN_LANDS_REGION_CODE") ENABLE, 
	 CONSTRAINT "TM_SALVTCD_FK" FOREIGN KEY ("SALVAGE_TYPE_CODE")
	  REFERENCES "THE"."SALVAGE_TYPE_CODE" ("SALVAGE_TYPE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."TM_TIMBER_MARK_UK2" ON "THE"."TIMBER_MARK" ("FOREST_FILE_ID", "CUTTING_PERMIT_ID") 
  ;
  CREATE UNIQUE INDEX "THE"."TM_TIMBER_MARK_UK1" ON "THE"."TIMBER_MARK" ("TIMBER_MARK", "FOREST_FILE_ID") 
  ;
  CREATE UNIQUE INDEX "THE"."TM_PK" ON "THE"."TIMBER_MARK" ("TIMBER_MARK") 
  ;
ALTER TABLE "THE"."TIMBER_MARK" ADD CONSTRAINT "TM_TIMBER_MARK_UK2" UNIQUE ("FOREST_FILE_ID", "CUTTING_PERMIT_ID")
  USING INDEX "THE"."TM_TIMBER_MARK_UK2"  ENABLE;
ALTER TABLE "THE"."TIMBER_MARK" ADD CONSTRAINT "TM_TIMBER_MARK_UK1" UNIQUE ("TIMBER_MARK", "FOREST_FILE_ID")
  USING INDEX "THE"."TM_TIMBER_MARK_UK1"  ENABLE;
ALTER TABLE "THE"."TIMBER_MARK" ADD CONSTRAINT "TM_PK" PRIMARY KEY ("TIMBER_MARK")
  USING INDEX "THE"."TM_PK"  ENABLE;

  CREATE TABLE "THE"."FIRE_HARVESTING_REASON_CODE" 
   (	"FIRE_HARVESTING_REASON_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."FHRC_PK" ON "THE"."FIRE_HARVESTING_REASON_CODE" ("FIRE_HARVESTING_REASON_CODE") 
  ;
ALTER TABLE "THE"."FIRE_HARVESTING_REASON_CODE" ADD CONSTRAINT "FHRC_PK" PRIMARY KEY ("FIRE_HARVESTING_REASON_CODE")
  USING INDEX "THE"."FHRC_PK"  ENABLE;

  CREATE TABLE "THE"."HARVEST_TYPE_CODE" 
   (	"HARVEST_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "HTC_PK" PRIMARY KEY ("HARVEST_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."HARVEST_AUTH_STATUS_CODE" 
   (	"HARVEST_AUTH_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "HASC_PK" PRIMARY KEY ("HARVEST_AUTH_STATUS_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."HARVEST_AUTH_EXTEND_REAS_CODE" 
   (	"HARVEST_AUTH_EXTEND_REAS_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "HAERC_PK" PRIMARY KEY ("HARVEST_AUTH_EXTEND_REAS_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."LICENCE_TO_CUT_CODE" 
   (	"LICENCE_TO_CUT_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."LTCCD_PK" ON "THE"."LICENCE_TO_CUT_CODE" ("LICENCE_TO_CUT_CODE") 
  ;
ALTER TABLE "THE"."LICENCE_TO_CUT_CODE" ADD CONSTRAINT "LTCCD_PK" PRIMARY KEY ("LICENCE_TO_CUT_CODE")
  USING INDEX "THE"."LTCCD_PK"  ENABLE;

  CREATE TABLE "THE"."HARVESTING_AUTHORITY" 
   (	"HVA_SKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"FOREST_FILE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CUTTING_PERMIT_ID" VARCHAR2(3), 
	"HARVESTING_AUTHORITY_ID" VARCHAR2(30), 
	"FOREST_DISTRICT" NUMBER(10,0) NOT NULL ENABLE, 
	"DISTRICT_ADMN_ZONE" VARCHAR2(4), 
	"GEOGRAPHIC_DISTRICT" NUMBER(10,0) NOT NULL ENABLE, 
	"MGMT_UNIT_ID" VARCHAR2(4), 
	"MGMT_UNIT_TYPE_CODE" VARCHAR2(1), 
	"LICENCE_TO_CUT_CODE" VARCHAR2(2), 
	"HARVEST_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"HARVEST_AUTH_STATUS_CODE" VARCHAR2(3), 
	"TENURE_TERM" NUMBER(5,0), 
	"STATUS_DATE" DATE, 
	"ISSUE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"EXTEND_DATE" DATE, 
	"EXTEND_COUNT" NUMBER(10,0), 
	"HARVEST_AUTH_EXTEND_REAS_CODE" VARCHAR2(1), 
	"QUOTA_TYPE_CODE" VARCHAR2(1), 
	"CROWN_LANDS_REGION_CODE" VARCHAR2(1), 
	"SALVAGE_TYPE_CODE" VARCHAR2(3), 
	"CASCADE_SPLIT_CODE" VARCHAR2(1), 
	"CATASTROPHIC_IND" VARCHAR2(1), 
	"CROWN_GRANTED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"CRUISE_BASED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"DECIDUOUS_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"BCAA_FOLIO_NUMBER" VARCHAR2(23), 
	"LOCATION" VARCHAR2(100), 
	"HIGHER_LEVEL_PLAN_REFERENCE" VARCHAR2(30), 
	"HARVEST_AREA" NUMBER(11,4), 
	"RETIREMENT_DATE" DATE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"IS_WASTE_ASSESSMENT_REQUIRED" VARCHAR2(1) DEFAULT 'U' NOT NULL ENABLE, 
	"IS_CP_EXTENSN_APPL_FEE_WAIVED" VARCHAR2(1) DEFAULT 'U' NOT NULL ENABLE, 
	"IS_CP_EXTENSION_APPL_FEE_PAID" VARCHAR2(1) DEFAULT 'U' NOT NULL ENABLE, 
	"IS_WITHIN_FIBRE_RECOVERY_ZONE" VARCHAR2(1) DEFAULT 'U' NOT NULL ENABLE, 
	"HARVESTING_AUTHORITY_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	 CONSTRAINT "HVA_IS_WASTE_ASSESS_REQ_CK" CHECK (IS_WASTE_ASSESSMENT_REQUIRED IN ('Y', 'N', 'U')) ENABLE, 
	 CONSTRAINT "AVCON_1148331360_DECID_000" CHECK (DECIDUOUS_IND IN ('N', 'Y')) ENABLE, 
	 CONSTRAINT "HVA_GUID_UK" UNIQUE ("HARVESTING_AUTHORITY_GUID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AVCON_1148331360_CROWN_000" CHECK (CROWN_GRANTED_IND IN ('N', 'Y')) ENABLE, 
	 CONSTRAINT "AVCON_1148331360_CRUIS_000" CHECK (CRUISE_BASED_IND IN ('N', 'Y')) ENABLE, 
	 CONSTRAINT "AVCON_1148331360_CATAS_000" CHECK (CATASTROPHIC_IND IN ('N', 'Y')) ENABLE, 
	 CONSTRAINT "HVA_IS_CP_EXT_APPL_FEE_WA_CK" CHECK (IS_CP_EXTENSN_APPL_FEE_WAIVED IN ('Y', 'N', 'U')) ENABLE, 
	 CONSTRAINT "HVA_IS_WITHIN_FRZ_CK" CHECK (IS_WITHIN_FIBRE_RECOVERY_ZONE IN ('Y', 'N', 'U')) ENABLE, 
	 CONSTRAINT "HVA_IS_CP_EXT_APPL_FEE_PA_CK" CHECK (IS_CP_EXTENSION_APPL_FEE_PAID IN ('Y', 'N', 'U')) ENABLE, 
	 CONSTRAINT "HVA_SALVTCD_FK" FOREIGN KEY ("SALVAGE_TYPE_CODE")
	  REFERENCES "THE"."SALVAGE_TYPE_CODE" ("SALVAGE_TYPE_CODE") ENABLE, 
	 CONSTRAINT "HVA_HTC_FK" FOREIGN KEY ("HARVEST_TYPE_CODE")
	  REFERENCES "THE"."HARVEST_TYPE_CODE" ("HARVEST_TYPE_CODE") ENABLE, 
	 CONSTRAINT "HVA_QTC_FK" FOREIGN KEY ("QUOTA_TYPE_CODE")
	  REFERENCES "THE"."QUOTA_TYPE_CODE" ("QUOTA_TYPE_CODE") ENABLE, 
	 CONSTRAINT "HVA_LTCCD_FK" FOREIGN KEY ("LICENCE_TO_CUT_CODE")
	  REFERENCES "THE"."LICENCE_TO_CUT_CODE" ("LICENCE_TO_CUT_CODE") ENABLE, 
	 CONSTRAINT "HVA_GEO_OU_FK" FOREIGN KEY ("GEOGRAPHIC_DISTRICT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "HVA_HAERC_FK" FOREIGN KEY ("HARVEST_AUTH_EXTEND_REAS_CODE")
	  REFERENCES "THE"."HARVEST_AUTH_EXTEND_REAS_CODE" ("HARVEST_AUTH_EXTEND_REAS_CODE") ENABLE, 
	 CONSTRAINT "HVA_CSC_FK" FOREIGN KEY ("CASCADE_SPLIT_CODE")
	  REFERENCES "THE"."CASCADE_SPLIT_CODE" ("CASCADE_SPLIT_CODE") ENABLE, 
	 CONSTRAINT "HVA_PFU_FK" FOREIGN KEY ("FOREST_FILE_ID")
	  REFERENCES "THE"."PROV_FOREST_USE" ("FOREST_FILE_ID") ENABLE, 
	 CONSTRAINT "HVA_HASC_FK" FOREIGN KEY ("HARVEST_AUTH_STATUS_CODE")
	  REFERENCES "THE"."HARVEST_AUTH_STATUS_CODE" ("HARVEST_AUTH_STATUS_CODE") ENABLE, 
	 CONSTRAINT "HVA_OU_FK" FOREIGN KEY ("FOREST_DISTRICT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "HVA_MUTC_FK" FOREIGN KEY ("MGMT_UNIT_TYPE_CODE")
	  REFERENCES "THE"."MGMT_UNIT_TYPE_CODE" ("MGMT_UNIT_TYPE_CODE") ENABLE, 
	 CONSTRAINT "HVA_CLRC_FK" FOREIGN KEY ("CROWN_LANDS_REGION_CODE")
	  REFERENCES "THE"."CROWN_LANDS_REGION_CODE" ("CROWN_LANDS_REGION_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."HVA_PK" ON "THE"."HARVESTING_AUTHORITY" ("HVA_SKEY") 
  ;
  CREATE UNIQUE INDEX "THE"."HVA_FF_CP_HVAID_UK" ON "THE"."HARVESTING_AUTHORITY" ("FOREST_FILE_ID", "CUTTING_PERMIT_ID", "HARVESTING_AUTHORITY_ID") 
  ;
ALTER TABLE "THE"."HARVESTING_AUTHORITY" ADD CONSTRAINT "HVA_PK" PRIMARY KEY ("HVA_SKEY")
  USING INDEX "THE"."HVA_PK"  ENABLE;
ALTER TABLE "THE"."HARVESTING_AUTHORITY" ADD CONSTRAINT "HVA_FF_CP_HVAID_UK" UNIQUE ("FOREST_FILE_ID", "CUTTING_PERMIT_ID", "HARVESTING_AUTHORITY_ID")
  USING INDEX "THE"."HVA_FF_CP_HVAID_UK"  ENABLE;

  CREATE TABLE "THE"."HAULING_AUTHORITY" 
   (	"TIMBER_MARK" VARCHAR2(6) NOT NULL ENABLE, 
	"FOREST_FILE_ID" VARCHAR2(10), 
	"MARKING_METHOD_CODE" VARCHAR2(1), 
	"MARKING_INSTRUMENT_CODE" VARCHAR2(1), 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"HAULING_AUTHORITY_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	 CONSTRAINT "HAA_GUID_UK" UNIQUE ("HAULING_AUTHORITY_GUID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "HAA_PK" PRIMARY KEY ("TIMBER_MARK")
  USING INDEX  ENABLE, 
	 CONSTRAINT "HAA_PFU_FK" FOREIGN KEY ("FOREST_FILE_ID")
	  REFERENCES "THE"."PROV_FOREST_USE" ("FOREST_FILE_ID") ENABLE, 
	 CONSTRAINT "HAA_MICD_FK" FOREIGN KEY ("MARKING_INSTRUMENT_CODE")
	  REFERENCES "THE"."MARKING_INSTRUMENT_CODE" ("MARKING_INSTRUMENT_CODE") ENABLE, 
	 CONSTRAINT "HAA_MMCD_FK" FOREIGN KEY ("MARKING_METHOD_CODE")
	  REFERENCES "THE"."MARKING_METHOD_CODE" ("MARKING_METHOD_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."CUT_BLOCK" 
   (	"CB_SKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"HVA_SKEY" NUMBER(10,0), 
	"FOREST_FILE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CUTTING_PERMIT_ID" VARCHAR2(3), 
	"TIMBER_MARK" VARCHAR2(10), 
	"CUT_BLOCK_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"SP_EXEMPT_IND" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"BLOCK_STATUS_DATE" DATE, 
	"CUT_BLOCK_DESCRIPTION" VARCHAR2(120), 
	"CUT_REGULATION_CODE" VARCHAR2(3), 
	"BLOCK_STATUS_ST" VARCHAR2(3) NOT NULL ENABLE, 
	"REFOREST_DECLARE_TYPE_CODE" VARCHAR2(3), 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"IS_WASTE_ASSESSMENT_REQUIRED" VARCHAR2(1) DEFAULT 'U' NOT NULL ENABLE, 
	"CUT_BLOCK_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"FIRE_HARVESTING_REASON_CODE" VARCHAR2(10), 
	"IS_UNDER_PARTITION_ORDER" VARCHAR2(1), 
	"REPORTED_FIRE_DATE" DATE, 
	 CONSTRAINT "CBLK_IS_WASTE_ASSESS_REQ_CK" CHECK (IS_WASTE_ASSESSMENT_REQUIRED IN ('Y', 'N', 'U')) ENABLE, 
	 CONSTRAINT "CBLK_UK4" UNIQUE ("HVA_SKEY", "TIMBER_MARK", "CUT_BLOCK_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CBLK_GUID_UK" UNIQUE ("CUT_BLOCK_GUID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CBLK_PK" PRIMARY KEY ("CB_SKEY")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AVCON_1054232647_SP_EX_000" CHECK (
SP_EXEMPT_IND IN ('N', 'Y')
) ENABLE, 
	 CONSTRAINT "CB_CRC_FK" FOREIGN KEY ("CUT_REGULATION_CODE")
	  REFERENCES "THE"."CUT_REGULATION_CODE" ("CUT_REGULATION_CODE") ENABLE, 
	 CONSTRAINT "CBLK_FHRC_FK" FOREIGN KEY ("FIRE_HARVESTING_REASON_CODE")
	  REFERENCES "THE"."FIRE_HARVESTING_REASON_CODE" ("FIRE_HARVESTING_REASON_CODE") ENABLE, 
	 CONSTRAINT "CB_HAA_FK" FOREIGN KEY ("TIMBER_MARK")
	  REFERENCES "THE"."HAULING_AUTHORITY" ("TIMBER_MARK") ENABLE, 
	 CONSTRAINT "CBLK_BSCD_FK" FOREIGN KEY ("BLOCK_STATUS_ST")
	  REFERENCES "THE"."BLOCK_STATUS_CODE" ("BLOCK_STATUS_CODE") ENABLE, 
	 CONSTRAINT "CBLK_TM_FK" FOREIGN KEY ("TIMBER_MARK")
	  REFERENCES "THE"."TIMBER_MARK" ("TIMBER_MARK") ENABLE, 
	 CONSTRAINT "CB_RDTC_FK" FOREIGN KEY ("REFOREST_DECLARE_TYPE_CODE")
	  REFERENCES "THE"."REFOREST_DECLARE_TYPE_CODE" ("REFOREST_DECLARE_TYPE_CODE") ENABLE, 
	 CONSTRAINT "CB_HVA_FK" FOREIGN KEY ("HVA_SKEY")
	  REFERENCES "THE"."HARVESTING_AUTHORITY" ("HVA_SKEY") ENABLE
   ) ;
  CREATE INDEX "THE"."CBLK_FF_TM_CB_I" ON "THE"."CUT_BLOCK" ("FOREST_FILE_ID", "TIMBER_MARK", "CUT_BLOCK_ID") 
  ;
ALTER TABLE "THE"."CUT_BLOCK" ADD CONSTRAINT "CBLK_TM_FF_CB_UK" UNIQUE ("TIMBER_MARK", "FOREST_FILE_ID", "CUT_BLOCK_ID")
  USING INDEX "THE"."CBLK_FF_TM_CB_I"  ENABLE;

  CREATE TABLE "THE"."RESULTS_AUDIT_EVENT" 
   (	"RESULTS_AUDIT_EVENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OPENING_ID" NUMBER(10,0), 
	"STANDARDS_REGIME_ID" NUMBER(10,0), 
	"SILVICULTURE_PROJECT_ID" NUMBER(10,0), 
	"RESULTS_AUDIT_ACTION_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"ACTION_DATE" DATE NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(2000), 
	"USER_ID" VARCHAR2(30), 
	"EMAIL_SENT_IND" VARCHAR2(1), 
	"XML_SUBMISSION_ID" NUMBER(10,0), 
	"OPENING_AMENDMENT_NUMBER" NUMBER(5,0), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "RAE_RAAC_FK" FOREIGN KEY ("RESULTS_AUDIT_ACTION_CODE")
	  REFERENCES "THE"."RESULTS_AUDIT_ACTION_CODE" ("RESULTS_AUDIT_ACTION_CODE") ENABLE
   )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "THE"."RAE_PK" ON "THE"."RESULTS_AUDIT_EVENT" ("RESULTS_AUDIT_EVENT_ID") 
  ;
ALTER TABLE "THE"."RESULTS_AUDIT_EVENT" ADD CONSTRAINT "RAE_PK" PRIMARY KEY ("RESULTS_AUDIT_EVENT_ID")
  USING INDEX "THE"."RAE_PK"  ENABLE;

  CREATE TABLE "THE"."RESULTS_AUDIT_DETAIL" 
   (	"RESULTS_AUDIT_DETAIL_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"RESULTS_AUDIT_EVENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BUSINESS_IDENTIFIER" VARCHAR2(30), 
	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"OLD_VALUE" VARCHAR2(250), 
	"NEW_VALUE" VARCHAR2(250), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "RAD_RAE_FK" FOREIGN KEY ("RESULTS_AUDIT_EVENT_ID")
	  REFERENCES "THE"."RESULTS_AUDIT_EVENT" ("RESULTS_AUDIT_EVENT_ID") ENABLE
   )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "THE"."RAD_PK" ON "THE"."RESULTS_AUDIT_DETAIL" ("RESULTS_AUDIT_DETAIL_ID") 
  ;
ALTER TABLE "THE"."RESULTS_AUDIT_DETAIL" ADD CONSTRAINT "RAD_PK" PRIMARY KEY ("RESULTS_AUDIT_DETAIL_ID")
  USING INDEX "THE"."RAD_PK"  ENABLE;

  CREATE TABLE "THE"."CUT_BLOCK_OPEN_ADMIN" 
   (	"CUT_BLOCK_OPEN_ADMIN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FOREST_FILE_ID" VARCHAR2(10), 
	"TIMBER_MARK" VARCHAR2(10), 
	"CUT_BLOCK_ID" VARCHAR2(10), 
	"CUTTING_PERMIT_ID" VARCHAR2(3), 
	"DISTURBANCE_GROSS_AREA" NUMBER(11,4), 
	"DISTURBANCE_START_DATE" DATE, 
	"DISTURBANCE_END_DATE" DATE, 
	"OPENING_ID" NUMBER(10,0), 
	"OPENING_GROSS_AREA" NUMBER(11,4), 
	"PLANNED_HARVEST_DATE" DATE, 
	"PLANNED_GROSS_BLOCK_AREA" NUMBER(11,4), 
	"PLANNED_NET_BLOCK_AREA" NUMBER(11,4), 
	"OPENING_PRIME_LICENCE_IND" VARCHAR2(1), 
	"CB_SKEY" NUMBER(10,0), 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CBOA_PK" PRIMARY KEY ("CUT_BLOCK_OPEN_ADMIN_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AVCON_1054232647_OPENI_000" CHECK (
OPENING_PRIME_LICENCE_IND IN ('N', 'Y')
) ENABLE, 
	 CONSTRAINT "CBOA_CB_FK" FOREIGN KEY ("CB_SKEY")
	  REFERENCES "THE"."CUT_BLOCK" ("CB_SKEY") ENABLE, 
	 CONSTRAINT "CBOA_O_FK" FOREIGN KEY ("OPENING_ID")
	  REFERENCES "THE"."OPENING" ("OPENING_ID") ENABLE
   ) ;
