
  CREATE TABLE "THE"."MIME_TYPE_CODE" 
   (	"MIME_TYPE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("MIME_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."OPENING_ATTACHMENT" 
   (	"OPENING_ATTACHMENT_FILE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OPENING_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ATTACHMENT_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"ATTACHMENT_DESCRIPTION" VARCHAR2(120), 
	"MIME_TYPE_CODE" VARCHAR2(3), 
	"ATTACHMENT_DATA" BLOB NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"OPENING_ATTACHMENT_GUID" RAW(16) DEFAULT sys_guid() NOT NULL ENABLE, 
	 CONSTRAINT "OPENING_ATTACHMENT_PK" PRIMARY KEY ("OPENING_ATTACHMENT_FILE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "OA_O_FK" FOREIGN KEY ("OPENING_ID")
	  REFERENCES "THE"."OPENING" ("OPENING_ID") ENABLE, 
	 CONSTRAINT "OA_MTC_FK" FOREIGN KEY ("MIME_TYPE_CODE")
	  REFERENCES "THE"."MIME_TYPE_CODE" ("MIME_TYPE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."OPATT_GUID_UK" ON "THE"."OPENING_ATTACHMENT" ("OPENING_ATTACHMENT_GUID") 
  ;
ALTER TABLE "THE"."OPENING_ATTACHMENT" ADD CONSTRAINT "OPATT_GUID_UK" UNIQUE ("OPENING_ATTACHMENT_GUID")
  USING INDEX "THE"."OPATT_GUID_UK"  ENABLE;
