
  CREATE TABLE "THE"."OPENING_AMENDMENT_HISTORY" 
   (	"OPENING_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OPENING_AMENDMENT_NUMBER" NUMBER(5,0) NOT NULL ENABLE, 
	"AMENDMENT_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"AMENDMENT_DATE" DATE NOT NULL ENABLE, 
	"SUBMITTED_BY_USERID" VARCHAR2(30), 
	"SUBMITTED_DATE" DATE, 
	"APP_ENT_BY_USERID" VARCHAR2(30), 
	"APPROVE_DATE" DATE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "OAH_PK" PRIMARY KEY ("OPENING_ID", "OPENING_AMENDMENT_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "OAH_O_FK" FOREIGN KEY ("OPENING_ID")
	  REFERENCES "THE"."OPENING" ("OPENING_ID") ENABLE
   ) ;
