
  CREATE TABLE "THE"."STOCKING_EVENT_HISTORY" 
   (	"STOCKING_EVENT_HISTORY_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OPENING_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OPENING_AMENDMENT_ID" NUMBER(10,0), 
	"OPENING_AMENDMENT_NUMBER" NUMBER(5,0), 
	"RESULTS_AUDIT_ACTION_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"SUBMITTED_USERID" VARCHAR2(30), 
	"RESULTS_SUBMISSION_ID" NUMBER(10,0), 
	"AMEND_EVENT_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SEH_PK" PRIMARY KEY ("STOCKING_EVENT_HISTORY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SEH_RAAC_FK" FOREIGN KEY ("RESULTS_AUDIT_ACTION_CODE")
	  REFERENCES "THE"."RESULTS_AUDIT_ACTION_CODE" ("RESULTS_AUDIT_ACTION_CODE") ENABLE, 
	 CONSTRAINT "SEH_OAH_FK" FOREIGN KEY ("OPENING_AMENDMENT_ID", "OPENING_AMENDMENT_NUMBER")
	  REFERENCES "THE"."OPENING_AMENDMENT_HISTORY" ("OPENING_ID", "OPENING_AMENDMENT_NUMBER") ENABLE, 
	 CONSTRAINT "SEH_O_FK" FOREIGN KEY ("OPENING_ID")
	  REFERENCES "THE"."OPENING" ("OPENING_ID") ENABLE
   ) ;
