
  CREATE TABLE "THE"."SILV_TREE_SPECIES_CODE" 
   (	"SILV_TREE_SPECIES_CODE" VARCHAR2(8) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."STSC_PK" ON "THE"."SILV_TREE_SPECIES_CODE" ("SILV_TREE_SPECIES_CODE") 
  ;
ALTER TABLE "THE"."SILV_TREE_SPECIES_CODE" ADD CONSTRAINT "STSC_PK" PRIMARY KEY ("SILV_TREE_SPECIES_CODE")
  USING INDEX "THE"."STSC_PK"  ENABLE;

  CREATE TABLE "THE"."SILV_SYSTEM_VARIANT_CODE" 
   (	"SILV_SYSTEM_VARIANT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SSVC_PK" ON "THE"."SILV_SYSTEM_VARIANT_CODE" ("SILV_SYSTEM_VARIANT_CODE") 
  ;
ALTER TABLE "THE"."SILV_SYSTEM_VARIANT_CODE" ADD CONSTRAINT "SSVC_PK" PRIMARY KEY ("SILV_SYSTEM_VARIANT_CODE")
  USING INDEX "THE"."SSVC_PK"  ENABLE;

  CREATE TABLE "THE"."SILV_TECHNIQUE_CODE" 
   (	"SILV_TECHNIQUE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."STC_PK" ON "THE"."SILV_TECHNIQUE_CODE" ("SILV_TECHNIQUE_CODE") 
  ;
ALTER TABLE "THE"."SILV_TECHNIQUE_CODE" ADD CONSTRAINT "STC_PK" PRIMARY KEY ("SILV_TECHNIQUE_CODE")
  USING INDEX "THE"."STC_PK"  ENABLE;

  CREATE TABLE "THE"."DISTURBANCE_CODE" 
   (	"DISTURBANCE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."DISTURBANCE_CODE_PK" ON "THE"."DISTURBANCE_CODE" ("DISTURBANCE_CODE") 
  ;
ALTER TABLE "THE"."DISTURBANCE_CODE" ADD CONSTRAINT "DISTURBANCE_CODE_PK" PRIMARY KEY ("DISTURBANCE_CODE")
  USING INDEX "THE"."DISTURBANCE_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."SILV_FUND_SRCE_CODE" 
   (	"SILV_FUND_SRCE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."TFC_PK" ON "THE"."SILV_FUND_SRCE_CODE" ("SILV_FUND_SRCE_CODE") 
  ;
ALTER TABLE "THE"."SILV_FUND_SRCE_CODE" ADD CONSTRAINT "TFC_PK" PRIMARY KEY ("SILV_FUND_SRCE_CODE")
  USING INDEX "THE"."TFC_PK"  ENABLE;

  CREATE TABLE "THE"."UNIT_BID_CODE" 
   (	"UNIT_BID_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "UBCD_PK" PRIMARY KEY ("UNIT_BID_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."SILV_PROJECT_STATUS_CODE" 
   (	"SILV_PROJECT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PSCD_PK" PRIMARY KEY ("SILV_PROJECT_STATUS_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."SILV_BASE_CODE" 
   (	"SILV_BASE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SBC_PK" ON "THE"."SILV_BASE_CODE" ("SILV_BASE_CODE") 
  ;
ALTER TABLE "THE"."SILV_BASE_CODE" ADD CONSTRAINT "SBC_PK" PRIMARY KEY ("SILV_BASE_CODE")
  USING INDEX "THE"."SBC_PK"  ENABLE;

  CREATE TABLE "THE"."CREW_CONTRACT_HIRE_CODE" 
   (	"CREW_CONTRACT_HIRE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CCHCD_PK" PRIMARY KEY ("CREW_CONTRACT_HIRE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."SILVICULTURE_PROJECT" 
   (	"SILVICULTURE_PROJECT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SILV_BASE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"FISCAL_YEAR" NUMBER(4,0) NOT NULL ENABLE, 
	"ORG_UNIT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"PROJECT_SEQUENCE" VARCHAR2(4) NOT NULL ENABLE, 
	"PROJECT_LOCATION" VARCHAR2(30), 
	"SILV_PROJECT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"VIEW_DATE" DATE, 
	"COORDINATOR_USERID" VARCHAR2(30), 
	"OVERHEAD_COST" NUMBER(9,2), 
	"CREW_CONTRACT_HIRE_CODE" VARCHAR2(1), 
	"DIST_ADMIN_ZONE" VARCHAR2(2), 
	"UNIT_BID_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "PROJ_PK" PRIMARY KEY ("SILVICULTURE_PROJECT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PROJ_SBC_FK" FOREIGN KEY ("SILV_BASE_CODE")
	  REFERENCES "THE"."SILV_BASE_CODE" ("SILV_BASE_CODE") ENABLE, 
	 CONSTRAINT "PROJ_SAZ_FK" FOREIGN KEY ("ORG_UNIT_NO", "DIST_ADMIN_ZONE")
	  REFERENCES "THE"."SILV_ADMIN_ZONE" ("ORG_UNIT_NO", "DIST_ADMIN_ZONE") ENABLE, 
	 CONSTRAINT "PROJ_UBCD_FK" FOREIGN KEY ("UNIT_BID_CODE")
	  REFERENCES "THE"."UNIT_BID_CODE" ("UNIT_BID_CODE") ENABLE, 
	 CONSTRAINT "PROJ_OU_FK" FOREIGN KEY ("ORG_UNIT_NO")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "PROJ_FC2_FK" FOREIGN KEY ("CLIENT_NUMBER")
	  REFERENCES "THE"."FOREST_CLIENT" ("CLIENT_NUMBER") ENABLE, 
	 CONSTRAINT "PROJ_PSCD_FK" FOREIGN KEY ("SILV_PROJECT_STATUS_CODE")
	  REFERENCES "THE"."SILV_PROJECT_STATUS_CODE" ("SILV_PROJECT_STATUS_CODE") ENABLE, 
	 CONSTRAINT "PROJ_CCHCD_FK" FOREIGN KEY ("CREW_CONTRACT_HIRE_CODE")
	  REFERENCES "THE"."CREW_CONTRACT_HIRE_CODE" ("CREW_CONTRACT_HIRE_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."SILV_CUT_PHASE_CODE" 
   (	"SILV_CUT_PHASE_CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SCPC_PK" ON "THE"."SILV_CUT_PHASE_CODE" ("SILV_CUT_PHASE_CODE") 
  ;
ALTER TABLE "THE"."SILV_CUT_PHASE_CODE" ADD CONSTRAINT "SCPC_PK" PRIMARY KEY ("SILV_CUT_PHASE_CODE")
  USING INDEX "THE"."SCPC_PK"  ENABLE;

  CREATE TABLE "THE"."SILV_OBJECTIVE_CODE" 
   (	"SILV_OBJECTIVE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SOC_PK" ON "THE"."SILV_OBJECTIVE_CODE" ("SILV_OBJECTIVE_CODE") 
  ;
ALTER TABLE "THE"."SILV_OBJECTIVE_CODE" ADD CONSTRAINT "SOC_PK" PRIMARY KEY ("SILV_OBJECTIVE_CODE")
  USING INDEX "THE"."SOC_PK"  ENABLE;

  CREATE TABLE "THE"."SILV_METHOD_CODE" 
   (	"SILV_METHOD_CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SMC_PK" ON "THE"."SILV_METHOD_CODE" ("SILV_METHOD_CODE") 
  ;
ALTER TABLE "THE"."SILV_METHOD_CODE" ADD CONSTRAINT "SMC_PK" PRIMARY KEY ("SILV_METHOD_CODE")
  USING INDEX "THE"."SMC_PK"  ENABLE;

  CREATE TABLE "THE"."SILV_ACTIVITY_MEASUREMENT_CODE" 
   (	"SILV_ACTIVITY_MEASUREMENT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SAM_PK" ON "THE"."SILV_ACTIVITY_MEASUREMENT_CODE" ("SILV_ACTIVITY_MEASUREMENT_CODE") 
  ;
ALTER TABLE "THE"."SILV_ACTIVITY_MEASUREMENT_CODE" ADD CONSTRAINT "SAM_PK" PRIMARY KEY ("SILV_ACTIVITY_MEASUREMENT_CODE")
  USING INDEX "THE"."SAM_PK"  ENABLE;

  CREATE TABLE "THE"."SILV_SYSTEM_CODE" 
   (	"SILV_SYSTEM_CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SSC_PK" ON "THE"."SILV_SYSTEM_CODE" ("SILV_SYSTEM_CODE") 
  ;
ALTER TABLE "THE"."SILV_SYSTEM_CODE" ADD CONSTRAINT "SSC_PK" PRIMARY KEY ("SILV_SYSTEM_CODE")
  USING INDEX "THE"."SSC_PK"  ENABLE;

  CREATE TABLE "THE"."ACTIVITY_TREATMENT_UNIT" 
   (	"ACTIVITY_TREATMENT_UNIT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ACTIVITY_TU_SEQ_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"ORG_UNIT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"OPENING_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SILVICULTURE_PROJECT_ID" NUMBER(10,0), 
	"PROJECT_UNIT_ID" NUMBER(6,0), 
	"SILV_BASE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"SILV_TECHNIQUE_CODE" VARCHAR2(2), 
	"SILV_METHOD_CODE" VARCHAR2(5), 
	"SILV_OBJECTIVE_CODE_1" VARCHAR2(3), 
	"SILV_OBJECTIVE_CODE_2" VARCHAR2(3), 
	"SILV_OBJECTIVE_CODE_3" VARCHAR2(3), 
	"SILV_FUND_SRCE_CODE" VARCHAR2(3), 
	"SILV_ACTIVITY_MEASUREMENT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"ACTIVITY_LICENSEE_ID" VARCHAR2(30), 
	"TREATMENT_AMOUNT" NUMBER(11,1), 
	"ACTUAL_TREATMENT_COST" NUMBER(9,0), 
	"ACT_PLANTED_NO" NUMBER(10,0), 
	"PLAN_SILV_TECHNIQUE_CODE" VARCHAR2(2), 
	"PLAN_SILV_METHOD_CODE" VARCHAR2(5), 
	"PLAN_SILV_FUND_SRCE_CODE" VARCHAR2(3), 
	"PLANNED_DATE" DATE, 
	"PLANNED_TREATMENT_AMOUNT" NUMBER(11,1), 
	"PLANNED_TREATMENT_COST" NUMBER(9,0), 
	"PLAN_SILV_OBJECTIVE_CODE_1" VARCHAR2(3), 
	"PLAN_SILV_OBJECTIVE_CODE_2" VARCHAR2(3), 
	"PLAN_SILV_OBJECTIVE_CODE_3" VARCHAR2(3), 
	"TARGET_PREPARED_SPOTS" NUMBER(4,0), 
	"PRUNING_MIN_CROWN_PCT" NUMBER(3,0), 
	"PRUNE_HEIGHT" NUMBER(3,1), 
	"STEMS_TO_PRUNE" NUMBER(4,0), 
	"MIN_ACCEPTABLE_DENSITY" NUMBER(4,0), 
	"TOTAL_STEMS_PER_HA" NUMBER(4,0), 
	"INTER_TREE_TARGET_DISTANCE" NUMBER(3,1), 
	"INTER_TREE_VARIATION" NUMBER(3,1), 
	"INTER_TREE_MIN_DISTANCE" NUMBER(3,1), 
	"MAX_TREES_PER_PLOT" NUMBER(2,0), 
	"MAX_TREES_PER_HA" NUMBER(4,0), 
	"SURVEY_PLANNED_NUM_PLOTS" NUMBER(4,0), 
	"SURVEY_ACTUAL_NUM_PLOTS" NUMBER(4,0), 
	"SURVEY_MIN_PLOTS_PER_STRATUM" NUMBER(10,0), 
	"SILV_TREE_SPECIES_CODE" VARCHAR2(8), 
	"ATU_START_DATE" DATE, 
	"ATU_COMPLETION_DATE" DATE, 
	"RESULTS_IND" VARCHAR2(1), 
	"UNIT_BID_PRICE" NUMBER(9,2), 
	"FIA_PROJECT_ID" VARCHAR2(10), 
	"RESULTS_SUBMISSION_ID" NUMBER(10,0), 
	"DISTURBANCE_CODE" VARCHAR2(3), 
	"SILV_SYSTEM_CODE" VARCHAR2(5), 
	"SILV_SYSTEM_VARIANT_CODE" VARCHAR2(3), 
	"SILV_CUT_PHASE_CODE" VARCHAR2(5), 
	"CUT_BLOCK_OPEN_ADMIN_ID" NUMBER(10,0), 
	"DISTURBANCE_COMPLETED_IND" VARCHAR2(1), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "ATU_SOC3_FK" FOREIGN KEY ("SILV_OBJECTIVE_CODE_3")
	  REFERENCES "THE"."SILV_OBJECTIVE_CODE" ("SILV_OBJECTIVE_CODE") ENABLE, 
	 CONSTRAINT "ATU_STC_PLND_FK" FOREIGN KEY ("PLAN_SILV_TECHNIQUE_CODE")
	  REFERENCES "THE"."SILV_TECHNIQUE_CODE" ("SILV_TECHNIQUE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SSVC_FK" FOREIGN KEY ("SILV_SYSTEM_VARIANT_CODE")
	  REFERENCES "THE"."SILV_SYSTEM_VARIANT_CODE" ("SILV_SYSTEM_VARIANT_CODE") ENABLE, 
	 CONSTRAINT "ATU_SOC1_FK" FOREIGN KEY ("SILV_OBJECTIVE_CODE_1")
	  REFERENCES "THE"."SILV_OBJECTIVE_CODE" ("SILV_OBJECTIVE_CODE") ENABLE, 
	 CONSTRAINT "ATU_RES_FK" FOREIGN KEY ("RESULTS_SUBMISSION_ID")
	  REFERENCES "THE"."RESULTS_ELECTRONIC_SUBMISSION" ("RESULTS_SUBMISSION_ID") ENABLE, 
	 CONSTRAINT "ATU_STSC_FK" FOREIGN KEY ("SILV_TREE_SPECIES_CODE")
	  REFERENCES "THE"."SILV_TREE_SPECIES_CODE" ("SILV_TREE_SPECIES_CODE") ENABLE, 
	 CONSTRAINT "ATU_SFSC_FK" FOREIGN KEY ("SILV_FUND_SRCE_CODE")
	  REFERENCES "THE"."SILV_FUND_SRCE_CODE" ("SILV_FUND_SRCE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SMC_PLND_FK" FOREIGN KEY ("PLAN_SILV_METHOD_CODE")
	  REFERENCES "THE"."SILV_METHOD_CODE" ("SILV_METHOD_CODE") ENABLE, 
	 CONSTRAINT "ATU_SOC_PLND3_FK" FOREIGN KEY ("PLAN_SILV_OBJECTIVE_CODE_3")
	  REFERENCES "THE"."SILV_OBJECTIVE_CODE" ("SILV_OBJECTIVE_CODE") ENABLE, 
	 CONSTRAINT "ATU_PROJ_FK" FOREIGN KEY ("SILVICULTURE_PROJECT_ID")
	  REFERENCES "THE"."SILVICULTURE_PROJECT" ("SILVICULTURE_PROJECT_ID") ENABLE, 
	 CONSTRAINT "ATU_STC_FK" FOREIGN KEY ("SILV_TECHNIQUE_CODE")
	  REFERENCES "THE"."SILV_TECHNIQUE_CODE" ("SILV_TECHNIQUE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SMC_FK" FOREIGN KEY ("SILV_METHOD_CODE")
	  REFERENCES "THE"."SILV_METHOD_CODE" ("SILV_METHOD_CODE") ENABLE, 
	 CONSTRAINT "ATU_DC_FK" FOREIGN KEY ("DISTURBANCE_CODE")
	  REFERENCES "THE"."DISTURBANCE_CODE" ("DISTURBANCE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SOC_PLND1_FK" FOREIGN KEY ("PLAN_SILV_OBJECTIVE_CODE_1")
	  REFERENCES "THE"."SILV_OBJECTIVE_CODE" ("SILV_OBJECTIVE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SOC_PLND2_FK" FOREIGN KEY ("PLAN_SILV_OBJECTIVE_CODE_2")
	  REFERENCES "THE"."SILV_OBJECTIVE_CODE" ("SILV_OBJECTIVE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SOC2_FK" FOREIGN KEY ("SILV_OBJECTIVE_CODE_2")
	  REFERENCES "THE"."SILV_OBJECTIVE_CODE" ("SILV_OBJECTIVE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SSC_FK" FOREIGN KEY ("SILV_SYSTEM_CODE")
	  REFERENCES "THE"."SILV_SYSTEM_CODE" ("SILV_SYSTEM_CODE") ENABLE, 
	 CONSTRAINT "ATU_OU_FK" FOREIGN KEY ("ORG_UNIT_NO")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "ATU_O_FK" FOREIGN KEY ("OPENING_ID")
	  REFERENCES "THE"."OPENING" ("OPENING_ID") ENABLE, 
	 CONSTRAINT "ATU_SCPC_FK" FOREIGN KEY ("SILV_CUT_PHASE_CODE")
	  REFERENCES "THE"."SILV_CUT_PHASE_CODE" ("SILV_CUT_PHASE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SFSC_PLND_FK" FOREIGN KEY ("PLAN_SILV_FUND_SRCE_CODE")
	  REFERENCES "THE"."SILV_FUND_SRCE_CODE" ("SILV_FUND_SRCE_CODE") ENABLE, 
	 CONSTRAINT "ATU_CBOA_FK" FOREIGN KEY ("CUT_BLOCK_OPEN_ADMIN_ID")
	  REFERENCES "THE"."CUT_BLOCK_OPEN_ADMIN" ("CUT_BLOCK_OPEN_ADMIN_ID") ENABLE, 
	 CONSTRAINT "ATU_SBC_FK" FOREIGN KEY ("SILV_BASE_CODE")
	  REFERENCES "THE"."SILV_BASE_CODE" ("SILV_BASE_CODE") ENABLE, 
	 CONSTRAINT "ATU_SAM_FK" FOREIGN KEY ("SILV_ACTIVITY_MEASUREMENT_CODE")
	  REFERENCES "THE"."SILV_ACTIVITY_MEASUREMENT_CODE" ("SILV_ACTIVITY_MEASUREMENT_CODE") ENABLE
   )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "THE"."ATU_PK" ON "THE"."ACTIVITY_TREATMENT_UNIT" ("ACTIVITY_TREATMENT_UNIT_ID") 
  ;
ALTER TABLE "THE"."ACTIVITY_TREATMENT_UNIT" ADD CONSTRAINT "ATU_PK" PRIMARY KEY ("ACTIVITY_TREATMENT_UNIT_ID")
  USING INDEX "THE"."ATU_PK"  ENABLE;
