
  CREATE TABLE "THE"."SILV_RELIEF_APPL_STATUS_CODE" 
   (	"SILV_RELIEF_APPL_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "SRASCD_PK" PRIMARY KEY ("SILV_RELIEF_APPL_STATUS_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."SILV_RELIEF_APPLICATION" 
   (	"SILV_RELIEF_APPLICATION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SILV_RELIEF_APPLICATION_NO" NUMBER(3,0) NOT NULL ENABLE, 
	"ACTIVITY_TREATMENT_UNIT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SILV_RELIEF_APPL_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"PRE_EVENT_FOREST_COVER_DATE" DATE NOT NULL ENABLE, 
	"POST_EVENT_FOREST_COVER_DATE" DATE NOT NULL ENABLE, 
	"AMENDMENT_OPENING_ID" NUMBER(10,0), 
	"OPENING_AMENDMENT_NUMBER" NUMBER(5,0), 
	"OBLIGATION_RELIEF_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"OBLIGATION_MET_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"CAUSE_DAMAGE_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"OFFICIALLY_INDUCED_ERROR_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"DUE_DILIGENCE_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"AUTHORIZATION_CHECKED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"SUBMITTED_DATE" DATE, 
	"SUBMITTED_BY_USERID" VARCHAR2(30), 
	"APPROVED_DATE" DATE, 
	"APPROVED_BY_USERID" VARCHAR2(30), 
	"REJECT_COMMENT" VARCHAR2(2000), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SRA_PK" PRIMARY KEY ("SILV_RELIEF_APPLICATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SRA_OAH_FK" FOREIGN KEY ("AMENDMENT_OPENING_ID", "OPENING_AMENDMENT_NUMBER")
	  REFERENCES "THE"."OPENING_AMENDMENT_HISTORY" ("OPENING_ID", "OPENING_AMENDMENT_NUMBER") ENABLE, 
	 CONSTRAINT "SRA_ATU_FK" FOREIGN KEY ("ACTIVITY_TREATMENT_UNIT_ID")
	  REFERENCES "THE"."ACTIVITY_TREATMENT_UNIT" ("ACTIVITY_TREATMENT_UNIT_ID") ENABLE, 
	 CONSTRAINT "SRA_SRASCD_FK" FOREIGN KEY ("SILV_RELIEF_APPL_STATUS_CODE")
	  REFERENCES "THE"."SILV_RELIEF_APPL_STATUS_CODE" ("SILV_RELIEF_APPL_STATUS_CODE") ENABLE
   ) ;
