
  CREATE TABLE "THE"."CUT_BLOCK_CLIENT_TYPE_CODE" 
   (	"CUT_BLOCK_CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CBCTC_PK" PRIMARY KEY ("CUT_BLOCK_CLIENT_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CUT_BLOCK_CLIENT" 
   (	"CBLK_CLIENT_SKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"CB_SKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"CUT_BLOCK_CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"LICENSEE_START_DATE" DATE, 
	"LICENSEE_END_DATE" DATE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CBC_PK" PRIMARY KEY ("CBLK_CLIENT_SKEY")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CBC_CBCTC_FK" FOREIGN KEY ("CUT_BLOCK_CLIENT_TYPE_CODE")
	  REFERENCES "THE"."CUT_BLOCK_CLIENT_TYPE_CODE" ("CUT_BLOCK_CLIENT_TYPE_CODE") ENABLE, 
	 CONSTRAINT "CBC_CB_FK" FOREIGN KEY ("CB_SKEY")
	  REFERENCES "THE"."CUT_BLOCK" ("CB_SKEY") ENABLE, 
	 CONSTRAINT "CBC_CL_FK" FOREIGN KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."CBC_UK" ON "THE"."CUT_BLOCK_CLIENT" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE", "CB_SKEY", "CUT_BLOCK_CLIENT_TYPE_CODE", "LICENSEE_START_DATE") 
  ;
ALTER TABLE "THE"."CUT_BLOCK_CLIENT" ADD CONSTRAINT "CBC_UK" UNIQUE ("CLIENT_NUMBER", "CLIENT_LOCN_CODE", "CB_SKEY", "CUT_BLOCK_CLIENT_TYPE_CODE", "LICENSEE_START_DATE")
  USING INDEX "THE"."CBC_UK"  ENABLE;
ALTER TABLE "THE"."CUT_BLOCK_CLIENT" ADD CONSTRAINT "CBC_UK2" UNIQUE ("CB_SKEY", "CLIENT_NUMBER", "CLIENT_LOCN_CODE", "CUT_BLOCK_CLIENT_TYPE_CODE", "LICENSEE_START_DATE")
  USING INDEX "THE"."CBC_UK"  ENABLE;
