
  CREATE TABLE "THE"."FILE_CLIENT_TYPE_CODE" 
   (	"FILE_CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."FCTC_PK" ON "THE"."FILE_CLIENT_TYPE_CODE" ("FILE_CLIENT_TYPE_CODE") 
  ;
ALTER TABLE "THE"."FILE_CLIENT_TYPE_CODE" ADD CONSTRAINT "FCTC_PK" PRIMARY KEY ("FILE_CLIENT_TYPE_CODE")
  USING INDEX "THE"."FCTC_PK"  ENABLE;
