
  CREATE TABLE "THE"."FOREST_FILE_CLIENT" 
   (	"FOREST_FILE_CLIENT_SKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"FOREST_FILE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"FOREST_FILE_CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"LICENSEE_START_DATE" DATE, 
	"LICENSEE_END_DATE" DATE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "FFC_CL_PK" PRIMARY KEY ("FOREST_FILE_CLIENT_SKEY")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FFC_FFCTC_FK" FOREIGN KEY ("FOREST_FILE_CLIENT_TYPE_CODE")
	  REFERENCES "THE"."FILE_CLIENT_TYPE_CODE" ("FILE_CLIENT_TYPE_CODE") ENABLE, 
	 CONSTRAINT "FFC_CL_FK" FOREIGN KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "FFC_PFU_FK" FOREIGN KEY ("FOREST_FILE_ID")
	  REFERENCES "THE"."PROV_FOREST_USE" ("FOREST_FILE_ID") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."FFC_CL_UK2" ON "THE"."FOREST_FILE_CLIENT" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE", "FOREST_FILE_ID", "FOREST_FILE_CLIENT_TYPE_CODE", "LICENSEE_START_DATE") 
  ;
ALTER TABLE "THE"."FOREST_FILE_CLIENT" ADD CONSTRAINT "FFC_CL_UK1" UNIQUE ("FOREST_FILE_ID", "FOREST_FILE_CLIENT_TYPE_CODE", "CLIENT_NUMBER", "CLIENT_LOCN_CODE", "LICENSEE_START_DATE")
  USING INDEX "THE"."FFC_CL_UK2"  ENABLE;
ALTER TABLE "THE"."FOREST_FILE_CLIENT" ADD CONSTRAINT "FFC_CL_UK2" UNIQUE ("CLIENT_NUMBER", "CLIENT_LOCN_CODE", "FOREST_FILE_ID", "FOREST_FILE_CLIENT_TYPE_CODE", "LICENSEE_START_DATE")
  USING INDEX "THE"."FFC_CL_UK2"  ENABLE;
