
  CREATE TABLE "THE"."FOR_CLIENT_LINK" 
   (	"FOR_CLIENT_LINK_SKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"FOREST_FILE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CUTTING_PERMIT_ID" VARCHAR2(3), 
	"CUT_BLOCK_ID" VARCHAR2(10), 
	"FILE_CLIENT_TYPE" VARCHAR2(1) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"LICENSEE_START_DT" DATE, 
	"LICENSEE_END_DATE" DATE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "FCL_PFU_FK" FOREIGN KEY ("FOREST_FILE_ID")
	  REFERENCES "THE"."PROV_FOREST_USE" ("FOREST_FILE_ID") ENABLE, 
	 CONSTRAINT "FCL_CL_FK" FOREIGN KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "FCL_FCTC_FK" FOREIGN KEY ("FILE_CLIENT_TYPE")
	  REFERENCES "THE"."FILE_CLIENT_TYPE_CODE" ("FILE_CLIENT_TYPE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."I1$_FOR_CLIENT_LINK" ON "THE"."FOR_CLIENT_LINK" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE", "FILE_CLIENT_TYPE", "FOREST_FILE_ID", "CUTTING_PERMIT_ID", "CUT_BLOCK_ID", "LICENSEE_START_DT") 
  ;
  CREATE UNIQUE INDEX "THE"."FCL_PK" ON "THE"."FOR_CLIENT_LINK" ("FOR_CLIENT_LINK_SKEY") 
  ;
ALTER TABLE "THE"."FOR_CLIENT_LINK" ADD CONSTRAINT "FCL_UK" UNIQUE ("FOREST_FILE_ID", "CUTTING_PERMIT_ID", "CUT_BLOCK_ID", "FILE_CLIENT_TYPE", "CLIENT_NUMBER", "CLIENT_LOCN_CODE", "LICENSEE_START_DT")
  USING INDEX "THE"."I1$_FOR_CLIENT_LINK"  ENABLE;
ALTER TABLE "THE"."FOR_CLIENT_LINK" ADD CONSTRAINT "FCL_PK" PRIMARY KEY ("FOR_CLIENT_LINK_SKEY")
  USING INDEX "THE"."FCL_PK"  ENABLE;
