version: '3.9'

x-frontend: &frontend
  environment:
    VITE_ZONE: DEV
    VITE_USER_POOLS_ID: ca-central-1_t2HSZBHur
    VITE_USER_POOLS_WEB_CLIENT_ID: 3g6n2ha1loi4kp1jhaq359vrvb
  healthcheck:
    test: curl http://localhost:3000"
    interval: 15s
    timeout: 5s
    retries: 5
  restart: always
  depends_on:
    backend:
      condition: service_healthy

x-backend: &backend
  healthcheck:
    test: curl -f http://localhost:8080/actuator/health | grep '"status":"UP"'
    interval: 5s
    timeout: 5s
    retries: 5
  restart: always

services:
  frontend:
    container_name: frontend
    entrypoint: sh -c "npm ci && npm run start"
    image: node:20-bullseye
    ports: ["3000:3000"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    working_dir: "/app"
    <<: *frontend

  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build: ./frontend
    ports: ["3005:3000"]
    volumes: ["./frontend/Caddyfile:/etc/caddy/Caddyfile"]
    <<: *frontend

  backend:
    container_name: backend
    entrypoint: sh -c './startup.sh && mvn -ntp spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5006"'
    #image: maven:3.9.6-amazoncorretto-21
    image: maven:3.9.6-eclipse-temurin-17
    network_mode: host
    volumes: ["./backend:/app"]
    working_dir: /app
    environment:
      DATABASE_HOST: nrcdb03.bcgov
      DATABASE_PORT: "1543"
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SERVICE_NAME: dbq01.nrs.bcgov
      ORACLEDB_KEYSTORE: /app/jssecacerts
      ORACLEDB_SECRET: changeit
    <<: *backend

  backend-native:
    container_name: backend-native
    profiles: ["native"]
    build: ./backend
    ports: ["8080:8080"]
    <<: *backend
