apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Module name
    value: nr-silva
  - name: COMPONENT
    description: Component name
    value: backend
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CPU_REQUEST
    value: "25m"
  - name: MEMORY_REQUEST
    value: "225Mi"
  - name: CPU_LIMIT
    value: "75m"
  - name: MEMORY_LIMIT
    value: "250Mi"
  - name: MIN_REPLICAS
    description: The minimum amount of replicas for the horizontal pod autoscaler.
    value: "3"
  - name: MAX_REPLICAS
    description: The maximum amount of replicas for the horizontal pod autoscaler.
    value: "5"
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: ORG_NAME
    description: Organization name, e.g. bcgov
    value: bcgov
  - name: DB_POOL_CONN_TIMEOUT
    description: Maximum number of milliseconds that a client will wait for a connection from the pool.
    value: "90000"
  - name: DB_POOL_IDLE_TIMEOUT
    description: Maximum amount of milliseconds that a connection is allowed to sit idle in the pool.
    value: "0"
  - name: DB_POOL_MAX_LIFETIME
    description: Maximum lifetime of a connection in the pool.
    value: "1800000"
  - name: RESULTS_ENV_OPENSEARCH
    description: Environment name for OpenSearch. # One of: development, test, production
    required: true
    value: development
  - name: DATABASE_HOST
    description: Where the database is hosted
    value: nrcdb03.bcgov
  - name: DATABASE_PORT
    description: The port to be used for the connection to the database
    value: "1543"
  - name: SERVICE_NAME
    description: The database's name
    value: dbq01.nrs.bcgov
  - name: ORACLEDB_KEYSTORE
    description: Keystore location path
    value: /app/jssecacerts
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: "${IMAGE_TAG}"
          from:
            kind: DockerImage
            name: ${REGISTRY}/${ORG_NAME}/${NAME}/${COMPONENT}:${ZONE}
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: ImageStreamTag
              name: "${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}"
      selector:
        deploymentconfig: "${NAME}-${ZONE}-${COMPONENT}"
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: "${NAME}-${ZONE}"
            deploymentconfig: "${NAME}-${ZONE}-${COMPONENT}"
        spec:
          containers:
            - image: "${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}"
              imagePullPolicy: Always
              name: "${NAME}"
              volumeMounts:
                - name: ${NAME}-${ZONE}-fluentbit-logs
                  mountPath: /logs
              env:
                - name: DB_POOL_CONN_TIMEOUT
                  value: ${DB_POOL_CONN_TIMEOUT}
                - name: DB_POOL_IDLE_TIMEOUT
                  value: ${DB_POOL_IDLE_TIMEOUT}
                - name: DB_POOL_MAX_LIFETIME
                  value: ${DB_POOL_MAX_LIFETIME}
                - name: RESULTS_ENV_OPENSEARCH
                  value: ${RESULTS_ENV_OPENSEARCH}
                - name: DATABASE_HOST
                  value: ${DATABASE_HOST}
                - name: DATABASE_PORT
                  value: ${DATABASE_PORT}
                - name: SERVICE_NAME
                  value: ${SERVICE_NAME}
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: oracle-user
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: oracle-password
                - name: ORACLEDB_KEYSTORE
                  value: ${ORACLEDB_KEYSTORE}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              readinessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 5
                timeoutSeconds: 10
                successThreshold: 1
                failureThreshold: 5
              livenessProbe:
                successThreshold: 1
                failureThreshold: 5
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
                timeoutSeconds: 5
          volumes:
            - name: ${NAME}-${ZONE}-fluentbit-logs
              persistentVolumeClaim:
                claimName: ${NAME}-${ZONE}-fluentbit-logs
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 80
          targetPort: 8080
      selector:
        deploymentconfig: "${NAME}-${ZONE}-${COMPONENT}"
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      host: "${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}"
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: "${NAME}-${ZONE}-${COMPONENT}"
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: "${NAME}-${ZONE}-${COMPONENT}"
      minReplicas: "${{MIN_REPLICAS}}"
      maxReplicas: "${{MAX_REPLICAS}}"
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 100
