CREATE TABLE silva.opening_tenure_association_history (
  opening_tenure_association_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cut_block_open_admin_id bigint NOT NULL REFERENCES silva.cut_block_open_admin(cut_block_open_admin_id),
  opening_id bigint NOT NULL REFERENCES silva.opening(opening_id),
  action varchar(12) NOT NULL CHECK (action IN ('ASSOCIATED', 'UNASSOCIATED')),
  forest_file_id varchar(10),
  cutting_permit_id varchar(3),
  cut_block_id varchar(10),
  timber_mark varchar(10),
  opening_prime_licence_ind varchar(1) CHECK (opening_prime_licence_ind IN ('Y', 'N')),
  revision_count integer NOT NULL,
  event_userid varchar(30) NOT NULL,
  event_timestamp timestamp(0) NOT NULL
);

CREATE INDEX opening_tenure_association_history_opening_i
  ON silva.opening_tenure_association_history (opening_id, event_timestamp);
