apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-postgis17
  labels:
    app: ubuntu-postgis17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-postgis17
  template:
    metadata:
      labels:
        app: ubuntu-postgis17
    spec:
      volumes:
        - name: postgis-data
          persistentVolumeClaim:
            claimName: postgis17-pvc
        - name: run-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
        - name: log-volume
          emptyDir: {}

      containers:
        - name: ubuntu-shell
          image: image-registry.openshift-image-registry.svc:5000/d41ea0-test/ubuntu-shell:latest
          env:
            - name: PATH
              value: /tmp:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          securityContext:
            runAsUser: 1016730000
            runAsGroup: 1016730000
            allowPrivilegeEscalation: false
          command:
            - /bin/bash
            - -lc
            - |
              set -euo pipefail
              export PATH="/tmp:${PATH}"
              cat <<'EOF' >/tmp/-c
              #!/bin/bash
              exec /bin/bash -c "$@"
              EOF
              cat <<'EOF' >/tmp/--
              #!/bin/bash
              exec /bin/bash "$@"
              EOF
              cat <<'EOF' >/tmp/ubuntu-shell
              #!/bin/bash
              exec /bin/bash "$@"
              EOF
              chmod +x /tmp/-c /tmp/-- /tmp/ubuntu-shell
              trap : TERM INT; sleep infinity & wait
          stdin: true
          tty: true
          volumeMounts:
            - name: postgis-data
              mountPath: /var/lib/postgresql

        - name: postgis
          image: postgis/postgis:17-3.4
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis17-secret
                  key: postgres-password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgis-data
              mountPath: /var/lib/postgresql
            - name: run-volume
              mountPath: /var/run/postgresql
            - name: tmp-volume
              mountPath: /tmp
            - name: log-volume
              mountPath: /var/log/postgresql
