name: Decision
description: Document a PO decision or change in project direction.
title: "[DECISION]: "
labels: [decision]
body:
  - type: markdown
    attributes:
      value: |
        **Document a key decision.**  
        This template helps clarify changes in project direction or priorities.

  - type: input
    id: decision_summary
    attributes:
      label: Decision Summary
      description: Summarize the decision being made.
      placeholder: e.g., Switch to microservices architecture.
      required: true

  - type: textarea
    id: decision_context
    attributes:
      label: Context
      description: Explain why this decision is being made.
      placeholder: e.g., Include background information, alternatives considered, or constraints.
      required: true

  - type: textarea
    id: impacted_areas
    attributes:
      label: Impacted Areas
      description: Describe what parts of the project will be affected by this decision.
      placeholder: e.g., Deployment strategy, team workflow, specific components, etc.
      render: shell

  - type: textarea
    id: decision_details
    attributes:
      label: Details
      description: Provide specific details about the decision.
      placeholder: e.g., Implementation plan, timeline, or expected outcomes.
      render: shell
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks and Mitigation
      description: Outline any risks associated with this decision and how to address them.
      placeholder: e.g., Delayed timelines, increased costs, or technical challenges.
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Add any supplementary notes, related tickets, or links.
      placeholder: e.g., Links to relevant documentation or meeting notes.
      render: shell
