-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.0.0.164;port=1525;service_name=DBDOCK_01

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
SET search_path = "silva",public;
ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_cboa_fk FOREIGN KEY (cut_block_open_admin_id) REFERENCES cut_block_open_admin(cut_block_open_admin_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_dc_fk FOREIGN KEY (disturbance_code) REFERENCES disturbance_code(disturbance_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_ou_fk FOREIGN KEY (org_unit_no) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_proj_fk FOREIGN KEY (silviculture_project_id) REFERENCES silviculture_project(silviculture_project_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_res_fk FOREIGN KEY (results_submission_id) REFERENCES results_electronic_submission(results_submission_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_sam_fk FOREIGN KEY (silv_activity_measurement_code) REFERENCES silv_activity_measurement_code(silv_activity_measurement_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_sbc_fk FOREIGN KEY (silv_base_code) REFERENCES silv_base_code(silv_base_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_scpc_fk FOREIGN KEY (silv_cut_phase_code) REFERENCES silv_cut_phase_code(silv_cut_phase_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_sfsc_fk FOREIGN KEY (silv_fund_srce_code) REFERENCES silv_fund_srce_code(silv_fund_srce_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_sfsc_plnd_fk FOREIGN KEY (plan_silv_fund_srce_code) REFERENCES silv_fund_srce_code(silv_fund_srce_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_smc_fk FOREIGN KEY (silv_method_code) REFERENCES silv_method_code(silv_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_smc_plnd_fk FOREIGN KEY (plan_silv_method_code) REFERENCES silv_method_code(silv_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_soc1_fk FOREIGN KEY (silv_objective_code_1) REFERENCES silv_objective_code(silv_objective_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_soc2_fk FOREIGN KEY (silv_objective_code_2) REFERENCES silv_objective_code(silv_objective_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_soc3_fk FOREIGN KEY (silv_objective_code_3) REFERENCES silv_objective_code(silv_objective_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_soc_plnd1_fk FOREIGN KEY (plan_silv_objective_code_1) REFERENCES silv_objective_code(silv_objective_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_soc_plnd2_fk FOREIGN KEY (plan_silv_objective_code_2) REFERENCES silv_objective_code(silv_objective_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_soc_plnd3_fk FOREIGN KEY (plan_silv_objective_code_3) REFERENCES silv_objective_code(silv_objective_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_ssc_fk FOREIGN KEY (silv_system_code) REFERENCES silv_system_code(silv_system_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_ssvc_fk FOREIGN KEY (silv_system_variant_code) REFERENCES silv_system_variant_code(silv_system_variant_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_stc_fk FOREIGN KEY (silv_technique_code) REFERENCES silv_technique_code(silv_technique_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_stc_plnd_fk FOREIGN KEY (plan_silv_technique_code) REFERENCES silv_technique_code(silv_technique_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_treatment_unit ADD CONSTRAINT atu_stsc_fk FOREIGN KEY (silv_tree_species_code) REFERENCES silv_tree_species_code(silv_tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE activity_tu_comment_link ADD CONSTRAINT acl_atu_fk FOREIGN KEY (activity_treatment_unit_id) REFERENCES activity_treatment_unit(activity_treatment_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE activity_tu_comment_link ADD CONSTRAINT acl_silvc_fk FOREIGN KEY (silviculture_comment_id) REFERENCES silviculture_comment(silviculture_comment_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE client_location ADD CONSTRAINT cl_fc_fk FOREIGN KEY (client_number) REFERENCES forest_client(client_number) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE client_location ADD CONSTRAINT cl_ou_fk FOREIGN KEY (update_org_unit) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE client_location ADD CONSTRAINT cl_ou_is_created_by_fk FOREIGN KEY (add_org_unit) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cut_block ADD CONSTRAINT cblk_bscd_fk FOREIGN KEY (block_status_st) REFERENCES block_status_code(block_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block ADD CONSTRAINT cblk_fhrc_fk FOREIGN KEY (fire_harvesting_reason_code) REFERENCES fire_harvesting_reason_code(fire_harvesting_reason_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block ADD CONSTRAINT cblk_tm_fk FOREIGN KEY (timber_mark) REFERENCES timber_mark(timber_mark) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block ADD CONSTRAINT cb_crc_fk FOREIGN KEY (cut_regulation_code) REFERENCES cut_regulation_code(cut_regulation_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block ADD CONSTRAINT cb_haa_fk FOREIGN KEY (timber_mark) REFERENCES hauling_authority(timber_mark) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block ADD CONSTRAINT cb_hva_fk FOREIGN KEY (hva_skey) REFERENCES harvesting_authority(hva_skey) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block ADD CONSTRAINT cb_rdtc_fk FOREIGN KEY (reforest_declare_type_code) REFERENCES reforest_declare_type_code(reforest_declare_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cut_block_client ADD CONSTRAINT cbc_cbctc_fk FOREIGN KEY (cut_block_client_type_code) REFERENCES cut_block_client_type_code(cut_block_client_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block_client ADD CONSTRAINT cbc_cb_fk FOREIGN KEY (cb_skey) REFERENCES cut_block(cb_skey) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block_client ADD CONSTRAINT cbc_cl_fk FOREIGN KEY (client_number,client_locn_code) REFERENCES client_location(client_number,client_locn_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cut_block_open_admin ADD CONSTRAINT cboa_cb_fk FOREIGN KEY (cb_skey) REFERENCES cut_block(cb_skey) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cut_block_open_admin ADD CONSTRAINT cboa_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE feature_classes ADD CONSTRAINT featur_cls_file_fk FOREIGN KEY (group_name_cd) REFERENCES storage_files(group_name_cd) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
-- ALTER TABLE forest_client ADD CONSTRAINT fc_citc_fk FOREIGN KEY (client_id_type_code) REFERENCES client_id_type_code(client_id_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

-- ALTER TABLE forest_client ADD CONSTRAINT fc_csc_fk FOREIGN KEY (client_status_code) REFERENCES client_status_code(client_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

-- ALTER TABLE forest_client ADD CONSTRAINT fc_ctcx_fk FOREIGN KEY (client_type_code,registry_company_type_code) REFERENCES client_type_company_xref(client_type_code,registry_company_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_client ADD CONSTRAINT fc_ou_fk FOREIGN KEY (add_org_unit) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_client ADD CONSTRAINT fc_ou_is_updated_by_fk FOREIGN KEY (update_org_unit) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover ADD CONSTRAINT fc_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_res_fk FOREIGN KEY (results_submission_id) REFERENCES results_electronic_submission(results_submission_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_scc1_fk FOREIGN KEY (stocking_class_code) REFERENCES stocking_class_code(stocking_class_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_scc2_fk FOREIGN KEY (site_class_code) REFERENCES site_class_code(site_class_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_sisc_fk FOREIGN KEY (site_index_source_code) REFERENCES site_index_source_code(site_index_source_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_src_fk FOREIGN KEY (silv_reserve_code) REFERENCES silv_reserve_code(silv_reserve_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_sroc_fk FOREIGN KEY (silv_reserve_objective_code) REFERENCES silv_reserve_objective_code(silv_reserve_objective_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_ssc6_fk FOREIGN KEY (stocking_status_code) REFERENCES stocking_status_code(stocking_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_ssu_fk FOREIGN KEY (stocking_standard_unit_id) REFERENCES stocking_standard_unit(stocking_standard_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_stc3_fk FOREIGN KEY (stocking_type_code) REFERENCES stocking_type_code(stocking_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_tcpc_fk FOREIGN KEY (tree_cover_pattern_code) REFERENCES tree_cover_pattern_code(tree_cover_pattern_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover ADD CONSTRAINT fc_tsc_fk FOREIGN KEY (tree_species_code) REFERENCES tree_species_code(tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_archive ADD CONSTRAINT fca_scc2_fk FOREIGN KEY (site_class_code) REFERENCES site_class_code(site_class_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive ADD CONSTRAINT fca_sisc_fk FOREIGN KEY (site_index_source_code) REFERENCES site_index_source_code(site_index_source_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive ADD CONSTRAINT fca_src_fk FOREIGN KEY (silv_reserve_code) REFERENCES silv_reserve_code(silv_reserve_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive ADD CONSTRAINT fca_sroc_fk FOREIGN KEY (silv_reserve_objective_code) REFERENCES silv_reserve_objective_code(silv_reserve_objective_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive ADD CONSTRAINT fca_ssc6_fk FOREIGN KEY (stocking_status_code) REFERENCES stocking_status_code(stocking_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive ADD CONSTRAINT fca_stc3_fk FOREIGN KEY (stocking_type_code) REFERENCES stocking_type_code(stocking_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive ADD CONSTRAINT fca_tcpc_fk FOREIGN KEY (tree_cover_pattern_code) REFERENCES tree_cover_pattern_code(tree_cover_pattern_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive ADD CONSTRAINT fca_tsc_fk FOREIGN KEY (tree_species_code) REFERENCES tree_species_code(tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_archive_geometry ADD CONSTRAINT fcag_cmc_fk FOREIGN KEY (capture_method_code) REFERENCES corp_capture_method(capture_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive_geometry ADD CONSTRAINT fcag_corpfcc_fk FOREIGN KEY (feature_class_skey) REFERENCES feature_classes(feature_class_skey) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive_geometry ADD CONSTRAINT fcag_dsc_fk FOREIGN KEY (data_source_code) REFERENCES data_source_code(data_source_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_archive_geometry ADD CONSTRAINT fcag_fca_fk FOREIGN KEY (forest_cover_id,archive_date) REFERENCES forest_cover_archive(forest_cover_id,archive_date) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_geometry ADD CONSTRAINT fcg_cmc_fk FOREIGN KEY (capture_method_code) REFERENCES corp_capture_method(capture_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_geometry ADD CONSTRAINT fcg_corpfcc_fk FOREIGN KEY (feature_class_skey) REFERENCES feature_classes(feature_class_skey) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_geometry ADD CONSTRAINT fcg_dsc_fk FOREIGN KEY (data_source_code) REFERENCES data_source_code(data_source_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_geometry ADD CONSTRAINT fcg_fc_fk FOREIGN KEY (forest_cover_id) REFERENCES forest_cover(forest_cover_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_layer ADD CONSTRAINT fclr_fc3_fk FOREIGN KEY (forest_cover_id) REFERENCES forest_cover(forest_cover_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_layer ADD CONSTRAINT fclr_fclc_fk FOREIGN KEY (forest_cover_layer_code) REFERENCES forest_cover_layer_code(forest_cover_layer_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_layer ADD CONSTRAINT fclr_ssc6_fk FOREIGN KEY (stocking_status_code) REFERENCES stocking_status_code(stocking_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_layer ADD CONSTRAINT fclr_stc3_fk FOREIGN KEY (stocking_type_code) REFERENCES stocking_type_code(stocking_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_layer_archive ADD CONSTRAINT fcla_fca_fk FOREIGN KEY (forest_cover_id,archive_date) REFERENCES forest_cover_archive(forest_cover_id,archive_date) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_layer_archive ADD CONSTRAINT fcla_fclc_fk FOREIGN KEY (forest_cover_layer_code) REFERENCES forest_cover_layer_code(forest_cover_layer_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_layer_archive ADD CONSTRAINT fcla_ssc6_fk FOREIGN KEY (stocking_status_code) REFERENCES stocking_status_code(stocking_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_layer_archive ADD CONSTRAINT fcla_stc3_fk FOREIGN KEY (stocking_type_code) REFERENCES stocking_type_code(stocking_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_layer_species ADD CONSTRAINT fcls_fclr_fk FOREIGN KEY (forest_cover_id,forest_cover_layer_id) REFERENCES forest_cover_layer(forest_cover_id,forest_cover_layer_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_layer_species ADD CONSTRAINT fcls_tsc_fk FOREIGN KEY (tree_species_code) REFERENCES tree_species_code(tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_layer_species_arc ADD CONSTRAINT fclsa_fcla_fk FOREIGN KEY (forest_cover_id,archive_date,forest_cover_layer_id) REFERENCES forest_cover_layer_archive(forest_cover_id,archive_date,forest_cover_layer_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_layer_species_arc ADD CONSTRAINT fclsa_tsc_fk FOREIGN KEY (tree_species_code) REFERENCES tree_species_code(tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_non_mapped_arc ADD CONSTRAINT fcnma1_fca_fk FOREIGN KEY (forest_cover_id,archive_date) REFERENCES forest_cover_archive(forest_cover_id,archive_date) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_non_mapped_arc ADD CONSTRAINT fcnma1_ssc6_fk FOREIGN KEY (stocking_status_code) REFERENCES stocking_status_code(stocking_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_non_mapped_arc ADD CONSTRAINT fcnma1_stc3_fk FOREIGN KEY (stocking_type_code) REFERENCES stocking_type_code(stocking_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_cover_non_mapped_area ADD CONSTRAINT fcnma_fc_fk FOREIGN KEY (forest_cover_id) REFERENCES forest_cover(forest_cover_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_non_mapped_area ADD CONSTRAINT fcnma_ssc6_fk FOREIGN KEY (stocking_status_code) REFERENCES stocking_status_code(stocking_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_cover_non_mapped_area ADD CONSTRAINT fcnma_stc3_fk FOREIGN KEY (stocking_type_code) REFERENCES stocking_type_code(stocking_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_file_client ADD CONSTRAINT ffc_cl_fk FOREIGN KEY (client_number,client_locn_code) REFERENCES client_location(client_number,client_locn_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_file_client ADD CONSTRAINT ffc_ffctc_fk FOREIGN KEY (forest_file_client_type_code) REFERENCES file_client_type_code(file_client_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forest_file_client ADD CONSTRAINT ffc_pfu_fk FOREIGN KEY (forest_file_id) REFERENCES prov_forest_use(forest_file_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_mgmt_unit ADD CONSTRAINT fmu_mutc_fk FOREIGN KEY (mgmt_unit_type_code) REFERENCES mgmt_unit_type_code(mgmt_unit_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forest_stewardship_plan ADD CONSTRAINT fsp_fspsc_fk FOREIGN KEY (fsp_status_code) REFERENCES fsp_status_code(fsp_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forhealth_rslt ADD CONSTRAINT fr_fclr_fk FOREIGN KEY (forest_cover_id,forest_cover_layer_id) REFERENCES forest_cover_layer(forest_cover_id,forest_cover_layer_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forhealth_rslt ADD CONSTRAINT fr_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forhealth_rslt ADD CONSTRAINT fr_sdac_fk FOREIGN KEY (silv_damage_agent_code) REFERENCES silv_damage_agent_code(silv_damage_agent_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forhealth_rslt_archive ADD CONSTRAINT fra_fcla_fk FOREIGN KEY (forest_cover_id,forest_cover_archive_date,forest_cover_layer_id) REFERENCES forest_cover_layer_archive(forest_cover_id,archive_date,forest_cover_layer_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE forhealth_rslt_archive ADD CONSTRAINT fra_sdac_fk FOREIGN KEY (silv_damage_agent_code) REFERENCES silv_damage_agent_code(silv_damage_agent_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE for_client_link ADD CONSTRAINT fcl_cl_fk FOREIGN KEY (client_number,client_locn_code) REFERENCES client_location(client_number,client_locn_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE for_client_link ADD CONSTRAINT fcl_fctc_fk FOREIGN KEY (file_client_type) REFERENCES file_client_type_code(file_client_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE for_client_link ADD CONSTRAINT fcl_pfu_fk FOREIGN KEY (forest_file_id) REFERENCES prov_forest_use(forest_file_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE fsp_standards_regime_xref ADD CONSTRAINT fspsrx_fsp_fk FOREIGN KEY (fsp_id,fsp_amendment_number) REFERENCES forest_stewardship_plan(fsp_id,fsp_amendment_number) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE fsp_standards_regime_xref ADD CONSTRAINT fspsrx_sr_fk FOREIGN KEY (standards_regime_id) REFERENCES standards_regime(standards_regime_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE harvesting_authority ADD CONSTRAINT hva_clrc_fk FOREIGN KEY (crown_lands_region_code) REFERENCES crown_lands_region_code(crown_lands_region_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_csc_fk FOREIGN KEY (cascade_split_code) REFERENCES cascade_split_code(cascade_split_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_geo_ou_fk FOREIGN KEY (geographic_district) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_haerc_fk FOREIGN KEY (harvest_auth_extend_reas_code) REFERENCES harvest_auth_extend_reas_code(harvest_auth_extend_reas_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_hasc_fk FOREIGN KEY (harvest_auth_status_code) REFERENCES harvest_auth_status_code(harvest_auth_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_htc_fk FOREIGN KEY (harvest_type_code) REFERENCES harvest_type_code(harvest_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_ltccd_fk FOREIGN KEY (licence_to_cut_code) REFERENCES licence_to_cut_code(licence_to_cut_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_mutc_fk FOREIGN KEY (mgmt_unit_type_code) REFERENCES mgmt_unit_type_code(mgmt_unit_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_ou_fk FOREIGN KEY (forest_district) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_pfu_fk FOREIGN KEY (forest_file_id) REFERENCES prov_forest_use(forest_file_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_qtc_fk FOREIGN KEY (quota_type_code) REFERENCES quota_type_code(quota_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvesting_authority ADD CONSTRAINT hva_salvtcd_fk FOREIGN KEY (salvage_type_code) REFERENCES salvage_type_code(salvage_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE harvest_sale ADD CONSTRAINT hs_ou_fk FOREIGN KEY (bcts_org_unit) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvest_sale ADD CONSTRAINT hs_pfu_fk FOREIGN KEY (forest_file_id) REFERENCES prov_forest_use(forest_file_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvest_sale ADD CONSTRAINT hs_pmcd_fk FOREIGN KEY (payment_method_cd) REFERENCES payment_method_code(payment_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvest_sale ADD CONSTRAINT hs_psccd FOREIGN KEY (plnd_sb_cat_code) REFERENCES sb_category_code(sb_category_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvest_sale ADD CONSTRAINT hs_smcd_fk FOREIGN KEY (sale_method_code) REFERENCES sale_method_code(sale_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvest_sale ADD CONSTRAINT hs_ssccd FOREIGN KEY (sold_sb_cat_code) REFERENCES sb_category_code(sb_category_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE harvest_sale ADD CONSTRAINT hs_stcd_fk FOREIGN KEY (sale_type_cd) REFERENCES sale_type_code(sale_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE hauling_authority ADD CONSTRAINT haa_micd_fk FOREIGN KEY (marking_instrument_code) REFERENCES marking_instrument_code(marking_instrument_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE hauling_authority ADD CONSTRAINT haa_mmcd_fk FOREIGN KEY (marking_method_code) REFERENCES marking_method_code(marking_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE hauling_authority ADD CONSTRAINT haa_pfu_fk FOREIGN KEY (forest_file_id) REFERENCES prov_forest_use(forest_file_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE opening ADD CONSTRAINT o_acc_fk FOREIGN KEY (prev_age_class_code) REFERENCES age_class_code(age_class_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_hcc_fk FOREIGN KEY (prev_height_class_code) REFERENCES height_class_code(height_class_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_occ_fk FOREIGN KEY (open_category_code) REFERENCES open_category_code(open_category_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_osc_fk FOREIGN KEY (opening_status_code) REFERENCES opening_status_code(opening_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_ou_fk FOREIGN KEY (admin_district_no) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_ou_resides_within_fk FOREIGN KEY (geo_district_no) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_res_fk FOREIGN KEY (results_submission_id) REFERENCES results_electronic_submission(results_submission_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_saz_fk FOREIGN KEY (org_unit_no,dist_admin_zone) REFERENCES silv_admin_zone(org_unit_no,dist_admin_zone) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_scc1_fk FOREIGN KEY (prev_stocking_class_code) REFERENCES stocking_class_code(stocking_class_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_scc2_fk FOREIGN KEY (prev_site_class_code) REFERENCES site_class_code(site_class_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_sisc_fk FOREIGN KEY (prev_site_index_source_code) REFERENCES site_index_source_code(site_index_source_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_ssc6_fk FOREIGN KEY (prev_stocking_status_code) REFERENCES stocking_status_code(stocking_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_tnc1_fk FOREIGN KEY (tsb_number_code) REFERENCES tsb_number_code(tsb_number_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_tsc1_fk FOREIGN KEY (prev_tree_spp1_code) REFERENCES tree_species_code(tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening ADD CONSTRAINT o_tsc2_fk FOREIGN KEY (prev_tree_spp2_code) REFERENCES tree_species_code(tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE opening_amendment_history ADD CONSTRAINT oah_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE opening_attachment ADD CONSTRAINT oa_mtc_fk FOREIGN KEY (mime_type_code) REFERENCES mime_type_code(mime_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening_attachment ADD CONSTRAINT oa_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE opening_comment_link ADD CONSTRAINT ocl_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening_comment_link ADD CONSTRAINT ocl_silvc_fk FOREIGN KEY (silviculture_comment_id) REFERENCES silviculture_comment(silviculture_comment_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE opening_geometry ADD CONSTRAINT og_cmc_fk FOREIGN KEY (capture_method_code) REFERENCES corp_capture_method(capture_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening_geometry ADD CONSTRAINT og_corpfcc_fk FOREIGN KEY (feature_class_skey) REFERENCES feature_classes(feature_class_skey) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening_geometry ADD CONSTRAINT og_dsc_fk FOREIGN KEY (data_source_code) REFERENCES data_source_code(data_source_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE opening_geometry ADD CONSTRAINT og_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE opening_land_status ADD CONSTRAINT ols_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE open_viewable_category ADD CONSTRAINT ovc_occ_fk FOREIGN KEY (open_category_code) REFERENCES open_category_code(open_category_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE open_viewable_category ADD CONSTRAINT ovc_osc_fk FOREIGN KEY (opening_status_code) REFERENCES opening_status_code(opening_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE planting_rslt ADD CONSTRAINT pr_atu_fk FOREIGN KEY (activity_treatment_unit_id) REFERENCES activity_treatment_unit(activity_treatment_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE planting_rslt ADD CONSTRAINT pr_sparri_fk FOREIGN KEY (request_skey,item_id) REFERENCES request_item(request_skey,item_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE planting_rslt ADD CONSTRAINT pr_stsc_fk FOREIGN KEY (silv_tree_species_code) REFERENCES silv_tree_species_code(silv_tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prov_forest_use ADD CONSTRAINT pfu_bcts_ou_fk FOREIGN KEY (bcts_org_unit) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE prov_forest_use ADD CONSTRAINT pfu_fmu_fk FOREIGN KEY (mgmt_unit_id,mgmt_unit_type) REFERENCES forest_mgmt_unit(mgmt_unit_id,mgmt_unit_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE prov_forest_use ADD CONSTRAINT pfu_ftcd_fk FOREIGN KEY (file_type_code) REFERENCES file_type_code(file_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE prov_forest_use ADD CONSTRAINT pfu_ou_fk FOREIGN KEY (forest_region) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE prov_forest_use ADD CONSTRAINT pfu_tfscd_fk FOREIGN KEY (file_status_st) REFERENCES tenure_file_status_code(tenure_file_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
-- ALTER TABLE request_item ADD CONSTRAINT spr_ri_sqatscd_fk FOREIGN KEY (seedlot_qa_test_status_code) REFERENCES seedlot_qa_test_status_code(seedlot_qa_test_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE results_audit_detail ADD CONSTRAINT rad_rae_fk FOREIGN KEY (results_audit_event_id) REFERENCES results_audit_event(results_audit_event_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE results_audit_event ADD CONSTRAINT rae_raac_fk FOREIGN KEY (results_audit_action_code) REFERENCES results_audit_action_code(results_audit_action_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE results_electronic_submission ADD CONSTRAINT res_cn_fk FOREIGN KEY (client_number,client_locn_code) REFERENCES client_location(client_number,client_locn_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE results_electronic_submission ADD CONSTRAINT res_ou_fk FOREIGN KEY (org_unit_no) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE silviculture_comment ADD CONSTRAINT silvc_scx_fk FOREIGN KEY (silv_comment_type_code,silv_comment_source_code) REFERENCES silv_comment_xref(silv_comment_type_code,silv_comment_source_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE silviculture_project ADD CONSTRAINT proj_cchcd_fk FOREIGN KEY (crew_contract_hire_code) REFERENCES crew_contract_hire_code(crew_contract_hire_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silviculture_project ADD CONSTRAINT proj_fc2_fk FOREIGN KEY (client_number) REFERENCES forest_client(client_number) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silviculture_project ADD CONSTRAINT proj_ou_fk FOREIGN KEY (org_unit_no) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silviculture_project ADD CONSTRAINT proj_pscd_fk FOREIGN KEY (silv_project_status_code) REFERENCES silv_project_status_code(silv_project_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silviculture_project ADD CONSTRAINT proj_saz_fk FOREIGN KEY (org_unit_no,dist_admin_zone) REFERENCES silv_admin_zone(org_unit_no,dist_admin_zone) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silviculture_project ADD CONSTRAINT proj_sbc_fk FOREIGN KEY (silv_base_code) REFERENCES silv_base_code(silv_base_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silviculture_project ADD CONSTRAINT proj_ubcd_fk FOREIGN KEY (unit_bid_code) REFERENCES unit_bid_code(unit_bid_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE silv_admin_zone ADD CONSTRAINT saz_ou_fk FOREIGN KEY (org_unit_no) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE silv_comment_xref ADD CONSTRAINT scx_scsc_fk FOREIGN KEY (silv_comment_source_code) REFERENCES silv_comment_source_code(silv_comment_source_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silv_comment_xref ADD CONSTRAINT scx_sctc_fk FOREIGN KEY (silv_comment_type_code) REFERENCES silv_comment_type_code(silv_comment_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE silv_project_comment_link ADD CONSTRAINT spcl_proj_fk FOREIGN KEY (silviculture_project_id) REFERENCES silviculture_project(silviculture_project_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silv_project_comment_link ADD CONSTRAINT spcl_silvc_fk FOREIGN KEY (silviculture_comment_id) REFERENCES silviculture_comment(silviculture_comment_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE silv_relief_application ADD CONSTRAINT sra_atu_fk FOREIGN KEY (activity_treatment_unit_id) REFERENCES activity_treatment_unit(activity_treatment_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silv_relief_application ADD CONSTRAINT sra_oah_fk FOREIGN KEY (amendment_opening_id,opening_amendment_number) REFERENCES opening_amendment_history(opening_id,opening_amendment_number) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE silv_relief_application ADD CONSTRAINT sra_srascd_fk FOREIGN KEY (silv_relief_appl_status_code) REFERENCES silv_relief_appl_status_code(silv_relief_appl_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE standards_regime ADD CONSTRAINT sr_srsc_fk FOREIGN KEY (standards_regime_status_code) REFERENCES standards_regime_status_code(standards_regime_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE standards_regime ADD CONSTRAINT sr_sstcd_fk FOREIGN KEY (silv_statute_code) REFERENCES silv_statute_code(silv_statute_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_comment_link ADD CONSTRAINT scl_silvc_fk FOREIGN KEY (silviculture_comment_id) REFERENCES silviculture_comment(silviculture_comment_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_comment_link ADD CONSTRAINT scl_ssu_fk FOREIGN KEY (stocking_standard_unit_id) REFERENCES stocking_standard_unit(stocking_standard_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_ecology ADD CONSTRAINT se_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_ecology ADD CONSTRAINT se_ssu_fk FOREIGN KEY (stocking_standard_unit_id) REFERENCES stocking_standard_unit(stocking_standard_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_ecology_archive ADD CONSTRAINT searc_ssuarc_fk FOREIGN KEY (stocking_event_history_id,stocking_standard_unit_id) REFERENCES stocking_standard_unit_archive(stocking_event_history_id,stocking_standard_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_event_history ADD CONSTRAINT seh_oah_fk FOREIGN KEY (opening_amendment_id,opening_amendment_number) REFERENCES opening_amendment_history(opening_id,opening_amendment_number) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_event_history ADD CONSTRAINT seh_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_event_history ADD CONSTRAINT seh_raac_fk FOREIGN KEY (results_audit_action_code) REFERENCES results_audit_action_code(results_audit_action_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_layer ADD CONSTRAINT sl_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_layer ADD CONSTRAINT sl_slc_fk FOREIGN KEY (stocking_layer_code) REFERENCES stocking_layer_code(stocking_layer_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_layer ADD CONSTRAINT sl_ssu_fk FOREIGN KEY (stocking_standard_unit_id) REFERENCES stocking_standard_unit(stocking_standard_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_layer ADD CONSTRAINT sl_tsuc_fk FOREIGN KEY (tree_size_unit_code) REFERENCES tree_size_unit_code(tree_size_unit_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_layer_archive ADD CONSTRAINT slarc_slc_fk FOREIGN KEY (stocking_layer_code) REFERENCES stocking_layer_code(stocking_layer_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_layer_archive ADD CONSTRAINT slarc_ssuarc_fk FOREIGN KEY (stocking_event_history_id,stocking_standard_unit_id) REFERENCES stocking_standard_unit_archive(stocking_event_history_id,stocking_standard_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_layer_archive ADD CONSTRAINT slarc_tsuc_fk FOREIGN KEY (tree_size_unit_code) REFERENCES tree_size_unit_code(tree_size_unit_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_layer_species ADD CONSTRAINT sls_sl_fk FOREIGN KEY (stocking_layer_id) REFERENCES stocking_layer(stocking_layer_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_layer_species ADD CONSTRAINT sls_stsc_fk FOREIGN KEY (silv_tree_species_code) REFERENCES silv_tree_species_code(silv_tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_layer_species_archive ADD CONSTRAINT slsarc_slarc_fk FOREIGN KEY (stocking_layer_id,stocking_event_history_id,stocking_standard_unit_id) REFERENCES stocking_layer_archive(stocking_layer_id,stocking_event_history_id,stocking_standard_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_layer_species_archive ADD CONSTRAINT slsarc_ssc1_fk FOREIGN KEY (silv_tree_species_code) REFERENCES silv_tree_species_code(silv_tree_species_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_milestone ADD CONSTRAINT sm_res_fk FOREIGN KEY (results_submission_id) REFERENCES results_electronic_submission(results_submission_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_milestone ADD CONSTRAINT sm_smtc_fk FOREIGN KEY (silv_milestone_type_code) REFERENCES silv_milestone_type_code(silv_milestone_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_milestone ADD CONSTRAINT sm_ssu_fk FOREIGN KEY (stocking_standard_unit_id) REFERENCES stocking_standard_unit(stocking_standard_unit_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_milestone_cmt_link ADD CONSTRAINT smcl_sc_fk FOREIGN KEY (silviculture_comment_id) REFERENCES silviculture_comment(silviculture_comment_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_milestone_cmt_link ADD CONSTRAINT smcl_sm_fk FOREIGN KEY (stocking_standard_unit_id,silv_milestone_type_code) REFERENCES stocking_milestone(stocking_standard_unit_id,silv_milestone_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_standard_unit ADD CONSTRAINT ssu_o_fk FOREIGN KEY (opening_id) REFERENCES opening(opening_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stocking_standard_unit ADD CONSTRAINT ssu_sr_fk FOREIGN KEY (standards_regime_id) REFERENCES standards_regime(standards_regime_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE stocking_standard_unit_archive ADD CONSTRAINT ssuarc_seh_fk FOREIGN KEY (stocking_event_history_id) REFERENCES stocking_event_history(stocking_event_history_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE timber_mark ADD CONSTRAINT tfalling_geographically_wit_fk FOREIGN KEY (geographic_distrct) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_cascd_fk FOREIGN KEY (cascade_split_code) REFERENCES cascade_split_code(cascade_split_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_clrc_fk FOREIGN KEY (lands_region) REFERENCES crown_lands_region_code(crown_lands_region_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_mercd_fk FOREIGN KEY (mark_extend_rsn_cd) REFERENCES mark_extension_reason_code(mark_extension_reason_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_micd_fk FOREIGN KEY (markng_instrmnt_cd) REFERENCES marking_instrument_code(marking_instrument_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_mmcd_fk FOREIGN KEY (marking_method_cd) REFERENCES marking_method_code(marking_method_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_ou_fk FOREIGN KEY (forest_district) REFERENCES org_unit(org_unit_no) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_pfu_fk FOREIGN KEY (forest_file_id) REFERENCES prov_forest_use(forest_file_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_qtcd_fk FOREIGN KEY (quota_type_code) REFERENCES quota_type_code(quota_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_salvtcd_fk FOREIGN KEY (salvage_type_code) REFERENCES salvage_type_code(salvage_type_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE timber_mark ADD CONSTRAINT tm_tscd_fk FOREIGN KEY (mark_status_st) REFERENCES tenure_file_status_code(tenure_file_status_code) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
