// Max length constraints for search input fields (based on database column definitions)
export const OPENING_ID_MAX_LENGTH = 10; // NUMBER(10,0)
export const FILE_ID_MAX_LENGTH = 10; // VARCHAR2(10)
export const LICENSEE_OPENING_ID_MAX_LENGTH = 30; // VARCHAR2(30)
export const CUT_BLOCK_MAX_LENGTH = 10; // VARCHAR2(10)
export const CUTTING_PERMIT_MAX_LENGTH = 3; // VARCHAR2(3)
export const TIMBER_MARK_MAX_LENGTH = 10; // VARCHAR2(10)
export const MAPSHEET_SQUARE_MAX_LENGTH = 3; // VARCHAR2(3)
export const OPENING_NUMBER_MAX_LENGTH = 4; // VARCHAR2(4)
