apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-postgis-pvc
  namespace: d41ea0-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: netapp-file-standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-postgis
  namespace: d41ea0-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-postgis
  template:
    metadata:
      labels:
        app: ubuntu-postgis
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        # Run the container with a high UID/GID to satisfy cluster security policies and scanners
        runAsUser: 20000
        runAsGroup: 20000
        fsGroup: 20000
      containers:
        - name: postgis
          # IMAGE placeholder; the CI workflow replaces IMAGE_PLACEHOLDER with the built image
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ubuntu-postgis-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ubuntu-postgis-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ubuntu-postgis-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data
            - name: tmp-volume
              mountPath: /tmp
            - name: run-volume
              mountPath: /var/run/postgresql
            - name: log-volume
              mountPath: /var/log/postgresql
          readinessProbe:
            exec:
              command: ["bash", "-c", "pg_isready -U postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["bash", "-c", "pg_isready -U postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: ubuntu-postgis-pvc
        - name: tmp-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
        - name: log-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-postgis-svc
  namespace: d41ea0-test
spec:
  selector:
    app: ubuntu-postgis
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
