apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ubuntu-postgis-template
  annotations:
    description: "Template for ubuntu-postgis deployment. Provide IMAGE when processing (e.g. oc process -f ... -p IMAGE=ghcr.io/owner/repo@sha256:...)"
parameters:
  - name: IMAGE
    description: Image to deploy for the postgis container (use digest form when possible)
    required: true
    value: "ghcr.io/bcgov/nr-silva/ubuntu-postgis"
  - name: NAMESPACE
    description: Target namespace
    required: true
    value: d41ea0-test
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ubuntu-postgis-pvc
      namespace: ${NAMESPACE}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: netapp-file-standard
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ubuntu-postgis
      namespace: ${NAMESPACE}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ubuntu-postgis
      template:
        metadata:
          labels:
            app: ubuntu-postgis
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: postgis
              # IMAGE must be provided via template parameter; avoid hard-coded :latest
              image: ${IMAGE}
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 5432
                  name: postgres
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: ubuntu-postgis-secret
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ubuntu-postgis-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: ubuntu-postgis-secret
                      key: POSTGRES_DB
              volumeMounts:
                - name: data-volume
                  mountPath: /var/lib/postgresql/data
                - name: tmp-volume
                  mountPath: /tmp
                - name: run-volume
                  mountPath: /var/run/postgresql
                - name: log-volume
                  mountPath: /var/log/postgresql
              readinessProbe:
                exec:
                  command: ["bash", "-c", "pg_isready -U $POSTGRES_USER"]
                initialDelaySeconds: 10
                periodSeconds: 5
              livenessProbe:
                exec:
                  command: ["bash", "-c", "pg_isready -U $POSTGRES_USER"]
                initialDelaySeconds: 30
                periodSeconds: 10
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "2Gi"
                  cpu: "1"
          volumes:
            - name: data-volume
              persistentVolumeClaim:
                claimName: ubuntu-postgis-pvc
            - name: tmp-volume
              emptyDir: {}
            - name: run-volume
              emptyDir: {}
            - name: log-volume
              emptyDir: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: ubuntu-postgis-svc
      namespace: ${NAMESPACE}
    spec:
      selector:
        app: ubuntu-postgis
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
