apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Module name
    value: nr-silva
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: AWS_ACCESS_KEY_ID
    description: AWS Access Key ID
    required: true
  - name: AWS_ACCESS_KEY_SECRET
    description: AWS Access Key Secret
    required: true
  - name: AWS_KINESIS_STREAM
    description: AWS Kinesis stream name
    required: true
  - name: AWS_KINESIS_ROLE_ARN
    description: AWS Kinesis Role ARN
    required: true
  - name: ORACLE_DB_USER
    description: Oracle database username for API
    required: true
  - name: ORACLE_DB_PASSWORD
    description: Oracle database password for API
    required: true
  - name: ORACLEDB_SECRET
    description: Oracle database keystore secret/password
    value: changeit
  - name: PG_DATABASE
    description: Postgres database name
    value: database
  - name: POSTGRES_DB_PASSWORD
    description: Password for the PostgreSQL connection user.
    required: true
  - name: FORESTCLIENTAPI_KEY
    description:
    required: true
  - name: VITE_USER_POOLS_WEB_CLIENT_ID
    description: Cognito user pools web client ID
    required: true
  - name: VITE_USER_POOLS_ID
    description: Cognito user pools ID
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-fluentbit
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      aws-access-key-id: ${AWS_ACCESS_KEY_ID}
      aws-access-key-secret: ${AWS_ACCESS_KEY_SECRET}
      aws-kinesis-stream: ${AWS_KINESIS_STREAM}
      aws-kinesis-role-arn: ${AWS_KINESIS_ROLE_ARN}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-backend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      oracle-user: ${ORACLE_DB_USER}
      oracle-password: ${ORACLE_DB_PASSWORD}
      oracle-secret: ${ORACLEDB_SECRET}
      forest-client-api-key: ${FORESTCLIENTAPI_KEY}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-${PG_DATABASE}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-name: ${NAME}
      database-password: ${POSTGRES_DB_PASSWORD}
      database-user: ${NAME}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-frontend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      vite-user-pools-web-client-id: ${VITE_USER_POOLS_WEB_CLIENT_ID}
      vite-user-pools-id: ${VITE_USER_POOLS_ID}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-results-backend-network-security-policy
    spec:
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
