apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Module name
    value: nr-silva
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: ORACLE_DB_USER
    description: Oracle database username for API
    required: true
  - name: ORACLE_DB_PASSWORD
    description: Oracle database password for API
    required: true
  - name: ORACLE_DB_HOST
    description: Oracle database hostname
    required: true
  - name: ORACLE_DB_SERVICE
    description: Oracle database service name
    required: true
  - name: ORACLEDB_SECRET
    description: Oracle database keystore secret/password
    value: changeit
  - name: PG_DATABASE
    description: Postgres database name
    value: database
  - name: POSTGRES_DB_PASSWORD
    description: Password for the PostgreSQL connection user.
    required: true
  - name: FORESTCLIENTAPI_KEY
    description:
    required: true
  - name: VITE_USER_POOLS_WEB_CLIENT_ID
    description: Cognito user pools web client ID
    required: true
  - name: VITE_USER_POOLS_ID
    description: Cognito user pools ID
    required: true
  - name: S3_BUCKET
    description: S3 bucket for RESULTS
    required: true
  - name: S3_ACCESS_KEY
    description: S3 bucket access key
    required: true
  - name: S3_SECRET_KEY
    description: S3 bucket secret key
    required: true
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}-${ZONE}-backend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      oracle-user: ${ORACLE_DB_USER}
      oracle-password: ${ORACLE_DB_PASSWORD}
      oracle-secret: ${ORACLEDB_SECRET}
      oracle-service: ${ORACLE_DB_SERVICE}
      oracle-host: ${ORACLE_DB_HOST}
      forest-client-api-key: ${FORESTCLIENTAPI_KEY}
      s3-bucket: ${S3_BUCKET}
      s3-access-key: ${S3_ACCESS_KEY}
      s3-secret-key: ${S3_SECRET_KEY}

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}-${ZONE}-${PG_DATABASE}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-name: ${NAME}
      database-password: ${POSTGRES_DB_PASSWORD}
      database-user: ${NAME}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}-${ZONE}-frontend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      vite-user-pools-web-client-id: ${VITE_USER_POOLS_WEB_CLIENT_ID}
      vite-user-pools-id: ${VITE_USER_POOLS_ID}
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-results-backend-network-security-policy
    spec:
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
