-- This table belongs to CLIENT. Is being added here just for the sake of the VIEW below.
-- Not all foreign keys are being added here. Only a few are added, because Silva will/should not
-- add data into the tables listed in here, so it is safe to assume that the foreign keys are respected

CREATE TABLE THE.FOREST_CLIENT (
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_NAME VARCHAR2(60) NOT NULL,
	LEGAL_FIRST_NAME VARCHAR2(30) NULL,
	LEGAL_MIDDLE_NAME VARCHAR2(30) NULL,
	CLIENT_STATUS_CODE VARCHAR2(3) NOT NULL,
	CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	BIRTHDATE DATE NULL,
	CLIENT_ID_TYPE_CODE VARCHAR2(4) NULL,
	CLIENT_IDENTIFICATION VARCHAR2(40) NULL,
	REGISTRY_COMPANY_TYPE_CODE VARCHAR2(4) NULL,
	CORP_REGN_NMBR VARCHAR2(9) NULL,
	CLIENT_ACRONYM VARCHAR2(8) NULL,
	WCB_FIRM_NUMBER VARCHAR2(6) NULL,
	OCG_SUPPLIER_NMBR VARCHAR2(10) NULL,
	CLIENT_COMMENT VARCHAR2(4000) NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT FOREST_CLIENT_PK PRIMARY KEY (CLIENT_NUMBER),
	CONSTRAINT SYS_C0029588_FC_CT CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0029589_FC_CT CHECK ("CLIENT_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0029590_FC_CT CHECK ("CLIENT_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029591_FC_CT CHECK ("CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029592_FC_CT CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029593_FC_CT CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029594_FC_CT CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0029595_FC_CT CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029596_FC_CT CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029597_FC_CT CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0029598_FC_CT CHECK ("REVISION_COUNT" IS NOT NULL)
);
CREATE UNIQUE INDEX FC_ACRONYM_I ON THE.FOREST_CLIENT (CLIENT_ACRONYM);
CREATE INDEX FC_CITC_FK_I ON THE.FOREST_CLIENT (CLIENT_ID_TYPE_CODE);
CREATE INDEX FC_CSC_FK_I ON THE.FOREST_CLIENT (CLIENT_STATUS_CODE);
CREATE INDEX FC_CTCX_FK_I ON THE.FOREST_CLIENT (CLIENT_TYPE_CODE,REGISTRY_COMPANY_TYPE_CODE);
CREATE INDEX FC_OU_FK_I ON THE.FOREST_CLIENT (ADD_ORG_UNIT);
CREATE INDEX FC_OU_IS_UPDATED_BY_FK_I ON THE.FOREST_CLIENT (UPDATE_ORG_UNIT);
CREATE UNIQUE INDEX "I2$_FOREST_CLIENT" ON THE.FOREST_CLIENT (CLIENT_NAME,LEGAL_FIRST_NAME,LEGAL_MIDDLE_NAME,CLIENT_NUMBER);
CREATE INDEX "I4$_FOREST_CLIENT" ON THE.FOREST_CLIENT (OCG_SUPPLIER_NMBR);
CREATE INDEX "I5$_FOREST_CLIENT" ON THE.FOREST_CLIENT (CORP_REGN_NMBR);

CREATE TABLE THE.CLIENT_LOCATION (
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	CLIENT_LOCN_NAME VARCHAR2(40) NULL,
	HDBS_COMPANY_CODE VARCHAR2(5) NULL,
	ADDRESS_1 VARCHAR2(40) NOT NULL,
	ADDRESS_2 VARCHAR2(40) NULL,
	ADDRESS_3 VARCHAR2(40) NULL,
	CITY VARCHAR2(30) NOT NULL,
	PROVINCE VARCHAR2(50) NULL,
	POSTAL_CODE VARCHAR2(10) NULL,
	COUNTRY VARCHAR2(50) NOT NULL,
	BUSINESS_PHONE VARCHAR2(10) NULL,
	HOME_PHONE VARCHAR2(10) NULL,
	CELL_PHONE VARCHAR2(10) NULL,
	FAX_NUMBER VARCHAR2(10) NULL,
	EMAIL_ADDRESS VARCHAR2(128) NULL,
	LOCN_EXPIRED_IND VARCHAR2(1) NOT NULL,
	RETURNED_MAIL_DATE DATE NULL,
	TRUST_LOCATION_IND VARCHAR2(1) NOT NULL,
	CLI_LOCN_COMMENT VARCHAR2(4000) NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT "BIN$A8NnKNSZAszgVAAQ4CNh2g==$0" CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSaAszgVAAQ4CNh2g==$0" CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSbAszgVAAQ4CNh2g==$0" CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNScAszgVAAQ4CNh2g==$0" CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSdAszgVAAQ4CNh2g==$0" CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSeAszgVAAQ4CNh2g==$0" CHECK ("REVISION_COUNT" IS NOT NULL),
	CONSTRAINT CLIENT_LOCATION_PK PRIMARY KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE),
	CONSTRAINT SYS_C0030524 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0030525 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0030526 CHECK ("ADDRESS_1" IS NOT NULL),
	CONSTRAINT SYS_C0030527 CHECK ("CITY" IS NOT NULL),
	CONSTRAINT SYS_C0030528 CHECK ("COUNTRY" IS NOT NULL),
	CONSTRAINT SYS_C0030529 CHECK ("LOCN_EXPIRED_IND" IS NOT NULL),
	CONSTRAINT SYS_C0030530 CHECK ("TRUST_LOCATION_IND" IS NOT NULL),
	CONSTRAINT SYS_C0030531 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);
CREATE INDEX CL_FC_FK_I ON THE.CLIENT_LOCATION (CLIENT_NUMBER);
CREATE INDEX CL_OU_FK_I ON THE.CLIENT_LOCATION (UPDATE_ORG_UNIT);
CREATE INDEX CL_OU_IS_CREATED_BY_FK_I ON THE.CLIENT_LOCATION (ADD_ORG_UNIT);
CREATE INDEX "I2$_CLIENT_LOCATION" ON THE.CLIENT_LOCATION (HDBS_COMPANY_CODE);


-- FTA Tables

CREATE TABLE THE.HARVEST_SALE (
	FOREST_FILE_ID VARCHAR2(10),
	SB_FUND_IND VARCHAR2(1) DEFAULT 'N' ,
	SALE_METHOD_CODE VARCHAR2(1),
	SALE_TYPE_CD VARCHAR2(2),
	PLANNED_SALE_DATE DATE,
	TENDER_OPENING_DT DATE,
	PLND_SB_CAT_CODE VARCHAR2(1),
	SOLD_SB_CAT_CODE VARCHAR2(1),
	TOTAL_BIDDERS NUMBER(5,0),
	LUMPSUM_BONUS_AMT NUMBER(11,2),
	CASH_SALE_EST_VOL NUMBER(13,2),
	CASH_SALE_TOT_DOL NUMBER(11,2),
	PAYMENT_METHOD_CD VARCHAR2(1),
	SALVAGE_IND VARCHAR2(1) DEFAULT 'N' ,
	SALE_VOLUME NUMBER(10,0),
	ADMIN_AREA_IND VARCHAR2(1) DEFAULT 'N' ,
	MINOR_FACILITY_IND VARCHAR2(1) DEFAULT 'N' ,
	BCTS_ORG_UNIT NUMBER(10,0),
	FTA_BONUS_BID NUMBER(11,2),
	FTA_BONUS_OFFER NUMBER(11,2),
	REVISION_COUNT NUMBER(5,0),
	ENTRY_USERID VARCHAR2(30),
	ENTRY_TIMESTAMP DATE,
	UPDATE_USERID VARCHAR2(30),
	UPDATE_TIMESTAMP DATE,
	CONSTRAINT AVCON_1054232647_ADMIN_000 CHECK (ADMIN_AREA_IND IN ('N', 'Y')),
	CONSTRAINT AVCON_1054232647_MINOR_000 CHECK (MINOR_FACILITY_IND IN ('N', 'Y')),
	CONSTRAINT AVCON_1054232647_SALVA_000 CHECK (SALVAGE_IND IN ('N', 'Y')),
	CONSTRAINT AVCON_1054232647_SB_FU_000 CHECK (SB_FUND_IND IN ('N', 'Y')),
	CONSTRAINT HS_PK PRIMARY KEY (FOREST_FILE_ID),
	CONSTRAINT HS_C_SYS_C0021608 CHECK ("FOREST_FILE_ID" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021609 CHECK ("SB_FUND_IND" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021610 CHECK ("SALVAGE_IND" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021611 CHECK ("ADMIN_AREA_IND" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021612 CHECK ("MINOR_FACILITY_IND" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021613 CHECK ("REVISION_COUNT" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021614 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021615 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021616 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT HS_C_SYS_C0021617 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);


CREATE TABLE THE.PAYMENT_METHOD_CODE (
	PAYMENT_METHOD_CODE VARCHAR2(1),
	DESCRIPTION VARCHAR2(120),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	UPDATE_TIMESTAMP DATE,
	CONSTRAINT PMCD_PK PRIMARY KEY (PAYMENT_METHOD_CODE),
	CONSTRAINT PMC_C_SYS_C0012233 CHECK ("PAYMENT_METHOD_CODE" IS NOT NULL),
	CONSTRAINT PMC_C_SYS_C0012234 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT PMC_C_SYS_C0012236 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT PMC_C_SYS_C0012238 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT PMC_C_SYS_C0012240 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.SB_CATEGORY_CODE (
	SB_CATEGORY_CODE VARCHAR2(1),
	DESCRIPTION VARCHAR2(120),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	UPDATE_TIMESTAMP DATE,
	CONSTRAINT SBCD_PK PRIMARY KEY (SB_CATEGORY_CODE),
	CONSTRAINT SB_C_SYS_C0012633 CHECK ("SB_CATEGORY_CODE" IS NOT NULL),
	CONSTRAINT SB_C_SYS_C0012635 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SB_C_SYS_C0012637 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SB_C_SYS_C0012639 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SB_C_SYS_C0012641 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);


CREATE TABLE THE.SALE_METHOD_CODE (
	SALE_METHOD_CODE VARCHAR2(1),
	DESCRIPTION VARCHAR2(120),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	UPDATE_TIMESTAMP DATE,
	CONSTRAINT SMDCD_PK PRIMARY KEY (SALE_METHOD_CODE),
	CONSTRAINT SMC_C_SYS_C0012265 CHECK ("SALE_METHOD_CODE" IS NOT NULL),
	CONSTRAINT SMC_C_SYS_C0012266 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SMC_C_SYS_C0012267 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SMC_C_SYS_C0012268 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SMC_C_SYS_C0012269 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.SALE_TYPE_CODE (
	SALE_TYPE_CODE VARCHAR2(2),
	DESCRIPTION VARCHAR2(120),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	UPDATE_TIMESTAMP DATE,
	CONSTRAINT STCD_PK PRIMARY KEY (SALE_TYPE_CODE),
	CONSTRAINT STC_C_SYS_C0010732 CHECK ("SALE_TYPE_CODE" IS NOT NULL),
	CONSTRAINT STC_C_SYS_C0010733 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT STC_C_SYS_C0010734 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT STC_C_SYS_C0010735 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT STC_C_SYS_C0010736 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

-- Global use table

-- Org unit doesn't belong to silva, but is accessed by the application
CREATE TABLE THE.ORG_UNIT (
	ORG_UNIT_NO NUMBER(10,0),
	ORG_UNIT_CODE VARCHAR2(6),
	ORG_UNIT_NAME VARCHAR2(100),
	LOCATION_CODE VARCHAR2(3),
	AREA_CODE VARCHAR2(3),
	TELEPHONE_NO VARCHAR2(7),
	ORG_LEVEL_CODE VARCHAR2(1),
	OFFICE_NAME_CODE VARCHAR2(2),
	ROLLUP_REGION_NO NUMBER(10,0),
	ROLLUP_REGION_CODE VARCHAR2(6),
	ROLLUP_DIST_NO NUMBER(10,0),
	ROLLUP_DIST_CODE VARCHAR2(6),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	UPDATE_TIMESTAMP DATE,
	CONSTRAINT ORG_UNIT_PK PRIMARY KEY (ORG_UNIT_NO),
	CONSTRAINT SYS_C0035144_OU_CT CHECK ("ORG_UNIT_NO" IS NOT NULL),
	CONSTRAINT SYS_C0035146_OU_CT CHECK ("ORG_UNIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0035148_OU_CT CHECK ("ORG_UNIT_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0035150_OU_CT CHECK ("LOCATION_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0035152_OU_CT CHECK ("AREA_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0035154_OU_CT CHECK ("TELEPHONE_NO" IS NOT NULL),
	CONSTRAINT SYS_C0035156_OU_CT CHECK ("ORG_LEVEL_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0035158_OU_CT CHECK ("OFFICE_NAME_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0035160_OU_CT CHECK ("ROLLUP_REGION_NO" IS NOT NULL),
	CONSTRAINT SYS_C0035162_OU_CT CHECK ("ROLLUP_REGION_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0035164_OU_CT CHECK ("ROLLUP_DIST_NO" IS NOT NULL),
	CONSTRAINT SYS_C0035166_OU_CT CHECK ("ROLLUP_DIST_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0035168_OU_CT CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0035169_OU_CT CHECK ("EXPIRY_DATE" IS NOT NULL)
);
CREATE UNIQUE INDEX "I2$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_CODE,ORG_UNIT_NO);
CREATE UNIQUE INDEX "I3$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_CODE);
CREATE UNIQUE INDEX "I4$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_NO,ORG_UNIT_CODE,ORG_UNIT_NAME,LOCATION_CODE,TELEPHONE_NO,ORG_LEVEL_CODE,OFFICE_NAME_CODE);
CREATE INDEX "I5$_ORG_UNIT" ON THE.ORG_UNIT (ROLLUP_DIST_CODE,ROLLUP_REGION_CODE);
CREATE INDEX "I6$_ORG_UNIT" ON THE.ORG_UNIT (ROLLUP_REGION_NO,ROLLUP_DIST_NO);
CREATE INDEX "I7$_ORG_UNIT" ON THE.ORG_UNIT (ROLLUP_REGION_CODE,ROLLUP_DIST_CODE);
CREATE UNIQUE INDEX "I8$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_NO,ORG_UNIT_CODE);
CREATE UNIQUE INDEX "I9$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_CODE,ORG_LEVEL_CODE,ORG_UNIT_NO,ORG_UNIT_NAME);

-- SPAR_REQUEST belongs to the SPAR system but is accessed by Silva for planting request IDs.
-- FK constraints referencing lookup tables not present in the test schema
-- (LOT_OWNERSHIP_CODE, SPAR_REQUEST_REGULATION_CODE) are omitted.
CREATE TABLE THE.SPAR_REQUEST (
	REQUEST_SKEY                    NUMBER(10,0),
	REQUEST_TYPE_CODE               VARCHAR2(3)      NOT NULL,
	SOWING_YEAR                     NUMBER(5,0)      NOT NULL,
	REQUEST_YEAR                    NUMBER(5,0)      NOT NULL,
	ORG_UNIT_NO                     NUMBER(10,0)     NOT NULL,
	REQUEST_SEQUENCE                NUMBER(5,0)      NOT NULL,
	SPR_REQUEST_STATUS_CODE         VARCHAR2(3)      NOT NULL,
	RQST_CLI_NUMBER                 VARCHAR2(8),
	RQST_CLI_LOCN_CD                VARCHAR2(2),
	DIST_ADMIN_ZONE                 VARCHAR2(2),
	INTENDED_USE_CODE               VARCHAR2(3),
	METHOD_OF_PAYMENT_CODE          VARCHAR2(3),
	REQUIRED_BY_DATE                DATE,
	PRIORITY_DATE                   DATE,
	AUTHORIZATION_CODE              VARCHAR2(3),
	SRVC_CLI_NUMBER                 VARCHAR2(8),
	SRVC_CLI_LOCN_CD                VARCHAR2(2),
	VEGETATION_CODE                 VARCHAR2(8),
	GENETIC_A_SPZ_CODE              VARCHAR2(3),
	GENETIC_B_SPZ_CODE              VARCHAR2(3),
	ELEVATION_SITE_MAX              NUMBER(5,0),
	ELEVATION_SITE_MIN              NUMBER(5,0),
	NAD_DATUM_CODE                  VARCHAR2(2),
	UTM_ZONE                        NUMBER(5,0),
	UTM_EASTING                     NUMBER(10,0),
	UTM_NORTHING                    NUMBER(10,0),
	LATITUDE_DEGREES                NUMBER(2,0)      NOT NULL,
	LATITUDE_MINUTES                NUMBER(2,0)      NOT NULL,
	LATITUDE_SECONDS                NUMBER(2,0),
	LONGITUDE_DEGREES               NUMBER(3,0)      NOT NULL,
	LONGITUDE_MINUTES               NUMBER(2,0)      NOT NULL,
	LONGITUDE_SECONDS               NUMBER(2,0),
	SEED_COAST_AREA_CODE            VARCHAR2(3),
	MAPSHEET_GRID                   VARCHAR2(3),
	MAPSHEET_LETTER                 VARCHAR2(1),
	MAPSHEET_SQUARE                 VARCHAR2(3),
	MAPSHEET_QUAD                   VARCHAR2(1),
	MAPSHEET_SUB_QUAD               VARCHAR2(1),
	OPENING_NUMBER                  VARCHAR2(4),
	SEEDLING_STOCK_TYPE_CODE        VARCHAR2(3),
	SEEDLING_CONTAINER_CODE         VARCHAR2(4),
	SEEDLING_STOCK_AGE_CODE         VARCHAR2(6),
	PLANTING_YEAR                   NUMBER(5,0),
	PLANTING_DAY                    VARCHAR2(4),
	PLANTING_SEASON_CODE            VARCHAR2(2),
	QTY_SEEDLINGS_RQST              NUMBER(6,1)      NOT NULL,
	LOT_CLI_NUMBER                  VARCHAR2(8),
	LOT_CLI_LOCN_CD                 VARCHAR2(2),
	LOT_OWNERSHIP_CODE              VARCHAR2(1),
	CROWN_LAND_IND                  VARCHAR2(1),
	SPAR_REQUEST_REGULATION_CODE    VARCHAR2(4),
	SPR_TENURE_CODE                 VARCHAR2(3),
	SPAR_FUND_SRCE_CODE             VARCHAR2(3),
	NURSRY_CLI_NUMBER               VARCHAR2(8),
	NURSRY_CLI_LOCN_CD              VARCHAR2(2),
	INTENDED_USE_LOCN               VARCHAR2(30),
	AUTHORIZED_BY_PRSN              VARCHAR2(30),
	CLIENT_REFERENCE                VARCHAR2(25),
	BGC_ZONE_CODE                   VARCHAR2(4),
	BGC_SUBZONE_CODE                VARCHAR2(3),
	VARIANT                         VARCHAR2(1),
	OPENING_ID                      NUMBER(10,0),
	RQST_CHANGED_IND                VARCHAR2(1)      NOT NULL,
	BATCH_JOB_ID                    VARCHAR2(8),
	BATCH_UPDATE_TS                 DATE,
	APPROVED_USERID                 VARCHAR2(30),
	APPROVED_TIMESTAMP              DATE,
	REQUEST_COMMENT                 VARCHAR2(2000),
	LOT_CROWN_PRIVATE_IND           VARCHAR2(1),
	INVOICING_EXCEPTION_IND         VARCHAR2(1)      NOT NULL,
	INVOICING_EXCEPTION_COMMENT     VARCHAR2(2000),
	INVOICING_EXCEPTION_USERID      VARCHAR2(30),
	INVOICING_EXCEPTION_DATE        DATE,
	CLIENT_PO_NUMBER                VARCHAR2(10),
	FIELD_CONTACT_NAME              VARCHAR2(40),
	FIELD_CONTACT_EMAIL_AND_PHONE   VARCHAR2(100),
	ENTRY_USERID                    VARCHAR2(30)     NOT NULL,
	ENTRY_TIMESTAMP                 DATE             NOT NULL,
	UPDATE_USERID                   VARCHAR2(30)     NOT NULL,
	UPDATE_TIMESTAMP                DATE             NOT NULL,
	REVISION_COUNT                  NUMBER(5,0)      NOT NULL,
	CONSTRAINT SPAR_REQUEST_PK PRIMARY KEY (REQUEST_SKEY),
	CONSTRAINT SPR_SR1_O_FK FOREIGN KEY (OPENING_ID) REFERENCES THE.OPENING(OPENING_ID)
);
CREATE UNIQUE INDEX "I1$_SPAR_REQUEST" ON THE.SPAR_REQUEST (REQUEST_TYPE_CODE,SOWING_YEAR,REQUEST_YEAR,ORG_UNIT_NO,REQUEST_SEQUENCE);
CREATE INDEX "I4$_SPAR_REQUEST" ON THE.SPAR_REQUEST (SOWING_YEAR,ORG_UNIT_NO,REQUEST_SEQUENCE);
CREATE INDEX "I7$_SPAR_REQUEST" ON THE.SPAR_REQUEST (ORG_UNIT_NO);
CREATE INDEX "I8$_SPAR_REQUEST" ON THE.SPAR_REQUEST (SPR_REQUEST_STATUS_CODE,REQUEST_SKEY);
CREATE INDEX SPR_SR1_O_FK_I ON THE.SPAR_REQUEST (OPENING_ID);
