-- This table belongs to CLIENT. Is being added here just for the sake of the VIEW below.
-- Not all foreign keys are being added here. Only a few are added, because Silva will/should not
-- add data into the tables listed in here, so it is safe to assume that the foreign keys are respected

CREATE TABLE THE.FOREST_CLIENT (
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_NAME VARCHAR2(60) NOT NULL,
	LEGAL_FIRST_NAME VARCHAR2(30) NULL,
	LEGAL_MIDDLE_NAME VARCHAR2(30) NULL,
	CLIENT_STATUS_CODE VARCHAR2(3) NOT NULL,
	CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	BIRTHDATE DATE NULL,
	CLIENT_ID_TYPE_CODE VARCHAR2(4) NULL,
	CLIENT_IDENTIFICATION VARCHAR2(40) NULL,
	REGISTRY_COMPANY_TYPE_CODE VARCHAR2(4) NULL,
	CORP_REGN_NMBR VARCHAR2(9) NULL,
	CLIENT_ACRONYM VARCHAR2(8) NULL,
	WCB_FIRM_NUMBER VARCHAR2(6) NULL,
	OCG_SUPPLIER_NMBR VARCHAR2(10) NULL,
	CLIENT_COMMENT VARCHAR2(4000) NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT FOREST_CLIENT_PK PRIMARY KEY (CLIENT_NUMBER),
	CONSTRAINT SYS_C0029588_FC_CT CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0029589_FC_CT CHECK ("CLIENT_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0029590_FC_CT CHECK ("CLIENT_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029591_FC_CT CHECK ("CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029592_FC_CT CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029593_FC_CT CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029594_FC_CT CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0029595_FC_CT CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029596_FC_CT CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029597_FC_CT CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0029598_FC_CT CHECK ("REVISION_COUNT" IS NOT NULL)
);
CREATE UNIQUE INDEX FC_ACRONYM_I ON THE.FOREST_CLIENT (CLIENT_ACRONYM);
CREATE INDEX FC_CITC_FK_I ON THE.FOREST_CLIENT (CLIENT_ID_TYPE_CODE);
CREATE INDEX FC_CSC_FK_I ON THE.FOREST_CLIENT (CLIENT_STATUS_CODE);
CREATE INDEX FC_CTCX_FK_I ON THE.FOREST_CLIENT (CLIENT_TYPE_CODE,REGISTRY_COMPANY_TYPE_CODE);
CREATE INDEX FC_OU_FK_I ON THE.FOREST_CLIENT (ADD_ORG_UNIT);
CREATE INDEX FC_OU_IS_UPDATED_BY_FK_I ON THE.FOREST_CLIENT (UPDATE_ORG_UNIT);
CREATE UNIQUE INDEX "I2$_FOREST_CLIENT" ON THE.FOREST_CLIENT (CLIENT_NAME,LEGAL_FIRST_NAME,LEGAL_MIDDLE_NAME,CLIENT_NUMBER);
CREATE INDEX "I4$_FOREST_CLIENT" ON THE.FOREST_CLIENT (OCG_SUPPLIER_NMBR);
CREATE INDEX "I5$_FOREST_CLIENT" ON THE.FOREST_CLIENT (CORP_REGN_NMBR);

CREATE TABLE THE.CLIENT_LOCATION (
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	CLIENT_LOCN_NAME VARCHAR2(40) NULL,
	HDBS_COMPANY_CODE VARCHAR2(5) NULL,
	ADDRESS_1 VARCHAR2(40) NOT NULL,
	ADDRESS_2 VARCHAR2(40) NULL,
	ADDRESS_3 VARCHAR2(40) NULL,
	CITY VARCHAR2(30) NOT NULL,
	PROVINCE VARCHAR2(50) NULL,
	POSTAL_CODE VARCHAR2(10) NULL,
	COUNTRY VARCHAR2(50) NOT NULL,
	BUSINESS_PHONE VARCHAR2(10) NULL,
	HOME_PHONE VARCHAR2(10) NULL,
	CELL_PHONE VARCHAR2(10) NULL,
	FAX_NUMBER VARCHAR2(10) NULL,
	EMAIL_ADDRESS VARCHAR2(128) NULL,
	LOCN_EXPIRED_IND VARCHAR2(1) NOT NULL,
	RETURNED_MAIL_DATE DATE NULL,
	TRUST_LOCATION_IND VARCHAR2(1) NOT NULL,
	CLI_LOCN_COMMENT VARCHAR2(4000) NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT "BIN$A8NnKNSZAszgVAAQ4CNh2g==$0" CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSaAszgVAAQ4CNh2g==$0" CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSbAszgVAAQ4CNh2g==$0" CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNScAszgVAAQ4CNh2g==$0" CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSdAszgVAAQ4CNh2g==$0" CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSeAszgVAAQ4CNh2g==$0" CHECK ("REVISION_COUNT" IS NOT NULL),
	CONSTRAINT CLIENT_LOCATION_PK PRIMARY KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE),
	CONSTRAINT SYS_C0030524 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0030525 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0030526 CHECK ("ADDRESS_1" IS NOT NULL),
	CONSTRAINT SYS_C0030527 CHECK ("CITY" IS NOT NULL),
	CONSTRAINT SYS_C0030528 CHECK ("COUNTRY" IS NOT NULL),
	CONSTRAINT SYS_C0030529 CHECK ("LOCN_EXPIRED_IND" IS NOT NULL),
	CONSTRAINT SYS_C0030530 CHECK ("TRUST_LOCATION_IND" IS NOT NULL),
	CONSTRAINT SYS_C0030531 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);
CREATE INDEX CL_FC_FK_I ON THE.CLIENT_LOCATION (CLIENT_NUMBER);
CREATE INDEX CL_OU_FK_I ON THE.CLIENT_LOCATION (UPDATE_ORG_UNIT);
CREATE INDEX CL_OU_IS_CREATED_BY_FK_I ON THE.CLIENT_LOCATION (ADD_ORG_UNIT);
CREATE INDEX "I2$_CLIENT_LOCATION" ON THE.CLIENT_LOCATION (HDBS_COMPANY_CODE);
