-- THE.FOREST_CLIENT foreign key
ALTER TABLE THE.FOREST_CLIENT ADD CONSTRAINT FC_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.FOREST_CLIENT ADD CONSTRAINT FC_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

-- THE.CLIENT_LOCATION foreign key
ALTER TABLE THE.CLIENT_LOCATION ADD CONSTRAINT CL_FC_FK FOREIGN KEY (CLIENT_NUMBER) REFERENCES THE.FOREST_CLIENT(CLIENT_NUMBER);
ALTER TABLE THE.CLIENT_LOCATION ADD CONSTRAINT CL_OU_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.CLIENT_LOCATION ADD CONSTRAINT CL_OU_IS_CREATED_BY_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

-- THE.FOREST_FILE_CLIENT foreign key
ALTER TABLE THE.FOREST_FILE_CLIENT ADD CONSTRAINT FFC_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);

-- THE.CUT_BLOCK_CLIENT foreign key
ALTER TABLE THE.CUT_BLOCK_CLIENT ADD CONSTRAINT CBC_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);

-- THE.FOR_CLIENT_LINK foreign key
ALTER TABLE THE.FOR_CLIENT_LINK ADD CONSTRAINT FCL_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);

-- THE.RESULTS_ELECTRONIC_SUBMISSION foreign key
ALTER TABLE THE.RESULTS_ELECTRONIC_SUBMISSION ADD CONSTRAINT RES_CN_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);

-- THE.SILVICULTURE_PROJECT foreign key
ALTER TABLE THE.SILVICULTURE_PROJECT ADD CONSTRAINT PROJ_FC2_FK FOREIGN KEY (CLIENT_NUMBER) REFERENCES THE.FOREST_CLIENT (CLIENT_NUMBER);


-- THE.HARVEST_SALE foreign keys
ALTER TABLE THE.HARVEST_SALE ADD CONSTRAINT HS_OU_FK FOREIGN KEY (BCTS_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.HARVEST_SALE ADD CONSTRAINT HS_PFU_FK FOREIGN KEY (FOREST_FILE_ID) REFERENCES THE.PROV_FOREST_USE(FOREST_FILE_ID);
ALTER TABLE THE.HARVEST_SALE ADD CONSTRAINT HS_PMCD_FK FOREIGN KEY (PAYMENT_METHOD_CD) REFERENCES THE.PAYMENT_METHOD_CODE(PAYMENT_METHOD_CODE);
ALTER TABLE THE.HARVEST_SALE ADD CONSTRAINT HS_PSCCD FOREIGN KEY (PLND_SB_CAT_CODE) REFERENCES THE.SB_CATEGORY_CODE(SB_CATEGORY_CODE);
ALTER TABLE THE.HARVEST_SALE ADD CONSTRAINT HS_SMCD_FK FOREIGN KEY (SALE_METHOD_CODE) REFERENCES THE.SALE_METHOD_CODE(SALE_METHOD_CODE);
ALTER TABLE THE.HARVEST_SALE ADD CONSTRAINT HS_SSCCD FOREIGN KEY (SOLD_SB_CAT_CODE) REFERENCES THE.SB_CATEGORY_CODE(SB_CATEGORY_CODE);
ALTER TABLE THE.HARVEST_SALE ADD CONSTRAINT HS_STCD_FK FOREIGN KEY (SALE_TYPE_CD) REFERENCES THE.SALE_TYPE_CODE(SALE_TYPE_CODE);

-- THE.OPENING foreign keys
ALTER TABLE THE.OPENING ADD CONSTRAINT O_OU_FK FOREIGN KEY (ADMIN_DISTRICT_NO) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.OPENING ADD CONSTRAINT O_OU_RESIDES_WITHIN_FK FOREIGN KEY (GEO_DISTRICT_NO) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

--- There is some FK references that are not properly identified in the model, This one references THE.CLIENT_LOCATION that belongs to the CLIENT application
ALTER TABLE THE.RESULTS_ELECTRONIC_SUBMISSION ADD CONSTRAINT RES_OU_FK FOREIGN KEY (ORG_UNIT_NO) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

ALTER TABLE THE.ACTIVITY_TREATMENT_UNIT ADD CONSTRAINT ATU_OU_FK FOREIGN KEY (ORG_UNIT_NO) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

ALTER TABLE THE.PROV_FOREST_USE ADD	CONSTRAINT PFU_BCTS_OU_FK FOREIGN KEY (BCTS_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

ALTER TABLE THE.PROV_FOREST_USE ADD CONSTRAINT PFU_OU_FK FOREIGN KEY (FOREST_REGION) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

ALTER TABLE THE.TIMBER_MARK ADD CONSTRAINT TFALLING_GEOGRAPHICALLY_WIT_FK FOREIGN KEY (GEOGRAPHIC_DISTRCT) REFERENCES THE.ORG_UNIT (ORG_UNIT_NO);
ALTER TABLE THE.TIMBER_MARK ADD CONSTRAINT TM_OU_FK FOREIGN KEY (FOREST_DISTRICT) REFERENCES THE.ORG_UNIT (ORG_UNIT_NO);

ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_GEO_OU_FK FOREIGN KEY (GEOGRAPHIC_DISTRICT) REFERENCES THE.ORG_UNIT (ORG_UNIT_NO);
ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_OU_FK FOREIGN KEY (FOREST_DISTRICT) REFERENCES THE.ORG_UNIT (ORG_UNIT_NO);

ALTER TABLE THE.SILVICULTURE_PROJECT ADD CONSTRAINT PROJ_OU_FK FOREIGN KEY (ORG_UNIT_NO) REFERENCES THE.ORG_UNIT (ORG_UNIT_NO);


ALTER TABLE THE.SILV_ADMIN_ZONE ADD CONSTRAINT SAZ_OU_FK FOREIGN KEY (ORG_UNIT_NO) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);