name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".github/**"
      - "!.github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  init:
    name: Initialize
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-24.04
    steps:
      # Get PR number for squash merges to main
      - id: pr
        uses: bcgov/action-get-pr@21f9351425cd55a98e869ee28919a512aa30647d # v0.0.1

  deploys-test:
    name: TEST Deploys (${{ needs.init.outputs.pr }})
    needs: [init]
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml
    with:
      backend_min_replicas: "1"
      backend_max_replicas: "1"
      allowed_origins: https://silva-test.nrs.gov.bc.ca/
      environment: test
      tag: ${{ needs.init.outputs.pr }}
      target: test

  e2e-on-test:
    name: E2E on Test environment
    needs: [deploys-test]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit
    with:
      target: test

  deploys-prod:
    name: PROD Deploys (${{ needs.init.outputs.pr }})
    needs: [init, deploys-test, e2e-on-test]
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml
    with:
      allowed_origins: https://silva.nrs.gov.bc.ca/
      environment: prod
      tag: ${{ needs.init.outputs.pr }}
      target: prod

  promote:
    name: Promote Images
    needs: [init, deploys-prod]
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, frontend]
    steps:
      - uses: shrink/actions-docker-registry-tag@f04afd0559f66b288586792eb150f45136a927fa # v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.init.outputs.pr }}
          tags: prod
