name: Merge

on:
  workflow_run:
    workflows: [PR Closed]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  init-test:
    name: TEST Init
    environment: test
    runs-on: ubuntu-22.04
    steps:
      - name: OpenShift Init
        uses: bcgov-nr/action-deployer-openshift@v1.0.4
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: common/openshift.init.yml
          overwrite: false
          parameters:
            -p ZONE=test -p NAME=${{ github.event.repository.name }}

  deploys-test:
    name: TEST Deployments
    needs: [init-test]
    environment: test
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    strategy:
      matrix:
        name: [database, backend, frontend]
        include:
          - name: database
          - name: backend
            verification_path: "actuator/health"
          - name: frontend
            parameters:
              -p VITE_USER_POOLS_ID=${{ vars.VITE_USER_POOLS_ID }}
              -p VITE_USER_POOLS_WEB_CLIENT_ID=${{ vars.VITE_USER_POOLS_WEB_CLIENT_ID }}
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v1.4.0
        with:
          file: ${{ matrix.name }}/openshift.deploy.yml
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: true
          parameters:
            -p ZONE=test
            -p NAME=${{ github.event.repository.name }}
            ${{ matrix.parameters }}
          penetration_test: true
          penetration_test_artifact: ${{ matrix.name }}
          penetration_test_issue: ${{ matrix.name }}
          penetration_test_token: ${{ secrets.GITHUB_SECRET }}

  init-prod:
    name: PROD Init
    needs: [deploys-test]
    environment: prod
    runs-on: ubuntu-22.04
    steps:
      - name: OpenShift Init
        uses: bcgov-nr/action-deployer-openshift@v1.0.4
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: common/openshift.init.yml
          overwrite: false
          parameters:
            -p ZONE=prod -p NAME=${{ github.event.repository.name }}

  deploys-prod:
    name: PROD Deployments
    needs: [init-prod]
    environment: prod
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [database, backend, frontend]
        include:
          - name: database
          - name: backend
            verification_path: "actuator/health"
          - name: frontend
            parameters:
              -p VITE_USER_POOLS_ID=${{ vars.VITE_USER_POOLS_ID }}
              -p VITE_USER_POOLS_WEB_CLIENT_ID=${{ vars.VITE_USER_POOLS_WEB_CLIENT_ID }}
              -p PROMOTE=${{ github.repository }}/frontend:test
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v1.4.0
        with:
          file: ${{ matrix.name }}/openshift.deploy.yml
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: true
          parameters:
            -p ZONE=prod
            -p NAME=${{ github.event.repository.name }}
            ${{ matrix.parameters }}

  image-promotions:
    name: Promote images to PROD
    needs: [deploys-prod]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        component: [database, backend, frontend]
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.component }}
          target: test
          tags: prod
