name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  init:
    name: Initialize
    concurrency:
      group: fam-routes-global
      cancel-in-progress: false
    outputs:
      hybrid_route_number: ${{ steps.allocate.outputs.route_hybrid }}
      postgres_route_number: ${{ steps.allocate.outputs.route_postgres }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Allocate FAM routes
        id: allocate
        uses: ./.github/actions/allocate-fam-routes
        with:
          oc_token: ${{ secrets.OC_TOKEN }}
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          pr_number: ${{ github.event.number }}

  validate:
    name: Validate PR
    needs: [init]
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@6d695dd755fa9255ea4bde335890516beb6f95e4 # v1.0.1
    permissions:
      pull-requests: write
    with:
      markdown_links: |
        - [Hybrid Backend](https://${{ github.event.repository.name }}-${{ github.event.number }}-hybrid-backend.apps.silver.devops.gov.bc.ca/actuator/health)
        - [Hybrid Frontend](https://${{ github.event.repository.name }}-${{ needs.init.outputs.hybrid_route_number }}-frontend.apps.silver.devops.gov.bc.ca)
        - [Postgres Backend](https://${{ github.event.repository.name }}-${{ github.event.number }}-postgres-backend.apps.silver.devops.gov.bc.ca/actuator/health)
        - [Postgres Frontend](https://${{ github.event.repository.name }}-${{ needs.init.outputs.postgres_route_number }}-frontend.apps.silver.devops.gov.bc.ca)

  results:
    name: Validate Results
    if: always()
    needs: [init, validate]
    runs-on: ubuntu-24.04
    steps:
      - run: |
          # View results
          echo "needs.*.result: ${{ toJson(needs.*.result) }}"

      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'canceled')
        run: |
          # Job failure found
          echo "At least one job has failed"
          exit 1
