name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  init:
    name: Initialize
    outputs:
      mod-tag: ${{ steps.mod-tag.outputs.mod-tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Number Mod 50
        id: mod-tag
        run: echo "mod-tag=$(( ${{ github.event.number }} % 50 ))" >> $GITHUB_OUTPUT

  validate:
    name: Validate PR
    needs: [init]
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@v0.8.3
    with:
      markdown_links: |
        - [Backend](https://${{ github.event.repository.name }}-${{ github.event.number }}-backend.apps.silver.devops.gov.bc.ca/actuator/health)
        - [Frontend](https://${{ github.event.repository.name }}-${{ needs.init.outputs.mod-tag }}-frontend.apps.silver.devops.gov.bc.ca)

  sysdig:
    name: Sysdig Monitoring Configuration
    runs-on: ubuntu-latest
    environment: tools
    steps:
      - name: Openshift sysdig config
        uses: bcgov-nr/action-deployer-openshift@v3.0.1
        with:
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: common/openshift.sysdig.yml
          overwrite: true

  results:
    name: Validate Results
    if: always()
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - run: |
          # View results
          echo "needs.*.result: ${{ toJson(needs.*.result) }}"

      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: |
          # Job failure found
          echo "At least one job has failed"
          exit 1
