name: PR Validate

on:
  workflow_run:
    workflows: ["PR"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.workflow_run.pull_requests[0].number }}
  cancel-in-progress: true

permissions: {}

jobs:
  get_routes:
    name: Get PR Routes
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Get all PR routes
        id: oc_routes
        uses: bcgov/action-oc-runner@v1.4.0
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          commands: |
            pr_number="${{ github.event.workflow_run.pull_requests[0].number }}"
            repo_name="${{ github.event.repository.name }}"
            oc get routes -o json > routes.json
            for type in hybrid postgres; do
              for comp in frontend backend; do
                route_name="${repo_name}-${pr_number}-${type}-${comp}"
                route_host=$(jq -r ".items[] | select(.metadata.name==\"$route_name\") | .spec.host" routes.json)
                echo "${type}_${comp}_host=$route_host" >> $GITHUB_OUTPUT
              done
            done
    outputs:
      hybrid_frontend_host: ${{ steps.oc_routes.outputs.hybrid_frontend_host }}
      hybrid_backend_host: ${{ steps.oc_routes.outputs.hybrid_backend_host }}
      postgres_frontend_host: ${{ steps.oc_routes.outputs.postgres_frontend_host }}
      postgres_backend_host: ${{ steps.oc_routes.outputs.postgres_backend_host }}

  validate:
    name: Validate PR
    needs: [get_routes]
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@6d695dd755fa9255ea4bde335890516beb6f95e4 # v1.0.1
    permissions:
      pull-requests: write
    with:
      markdown_links: |
        - [Hybrid Backend](https://${{ needs.get_routes.outputs.hybrid_backend_host }}/actuator/health)
        - [Hybrid Frontend](https://${{ needs.get_routes.outputs.hybrid_frontend_host }})
        - [Postgres Backend](https://${{ needs.get_routes.outputs.postgres_backend_host }}/actuator/health)
        - [Postgres Frontend](https://${{ needs.get_routes.outputs.postgres_frontend_host }})

  results:
    name: Validate Results
    if: always()
    needs: [validate]
    runs-on: ubuntu-24.04
    steps:
      - run: |
          # View results
          echo "needs.*.result: ${{ toJson(needs.*.result) }}"

      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: |
          # Job failure found
          echo "At least one job has failed"
          exit 1
