name: SchemaSpy

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    branches: [main]
    paths:
      - "backend/src/main/resources/db/migration/**"
      - "backend/src/main/resources/db/migration-dev/**"
  workflow_dispatch:

permissions: {}

jobs:
  schemaspy:
    name: Generate SchemaSpy Documentation and Push to GitHub Pages
    permissions:
      contents: write
      pages: write
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.schema-spy.yml@a11ad3d1b9288fb40757c4314a62eb86ff227931 # v1.2.1
    with:
      flyway_locations: >-
        filesystem:./backend/src/main/resources/db/migration,
        filesystem:./backend/src/main/resources/db/migration-dev
      flyway_schema: silva
      schemaspy_schema: silva
