name: SchemaSpy

on:
  push:
    branches: [feat/1177-setup-schemaspy-on-postgresql-database]
    paths:
      - "backend/src/main/resources/db/migration/**"
      - "backend/src/main/resources/db/migration-dev/**"
  workflow_dispatch:

permissions: {}

jobs:
  schemaspy:
    name: Generate SchemaSpy Documentation and Push to GitHub Pages
    permissions:
      contents: write
      pages: write
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.schema-spy.yml@ca6579bdadf383a2513397081f963889b92823a4 # v1.1.0
    with:
      flyway_locations: >-
        filesystem:./backend/src/main/resources/db/migration,
        filesystem:./backend/src/main/resources/db/migration-dev
      flyway_schema: silva
      schemaspy_schema: silva
