name: Unit Tests and Analysis

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # tests:
  #   name: Unit Tests
  #   if: github.event_name != 'pull_request' || !github.event.pull_request.draft
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: bcgov-nr/action-test-and-analyse@v1.0.0
  #       with:
  #         commands: |
  #           npm ci
  #           npm run test
  #         dir: frontend
  #         node_version: "20"
  #         sonar_args: >
  #           -Dsonar.exclusions=**/coverage/**,**/node_modules/**,**/*spec.ts
  #           -Dsonar.organization=bcgov-sonarcloud
  #           -Dsonar.project.monorepo.enabled=true
  #           -Dsonar.projectKey=nr-silva
  #           -Dsonar.sources=src
  #           -Dsonar.tests.inclusions=**/*spec.ts
  #           -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
  #         sonar_token: ${{ secrets.SONAR_TOKEN }}
  #         triggers: ('frontend/')

  # https://github.com/marketplace/actions/aqua-security-trivy
  trivy:
    name: Trivy Security Scan
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.11.2
        with:
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          scan-type: "fs"
          scanners: "vuln,secret,config"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
